#include "runtime/math_objects/LatheProfile.hpp"
#include "runtime/math_objects/LatheGeometry.hpp"
#include "runtime/math_objects/MathObjects.hpp"
#include "scene/MathObjectScene.hpp"
#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <limits>
#include <set>
#include <stdexcept>
#include <string>

namespace {
using namespace paths;
constexpr double pi=3.14159265358979323846;
unsigned certificates=0,meshes=0;std::size_t maxVertices=0,maxIndices=0;
void require(bool v,const char* message){if(!v)throw std::runtime_error(message);}
void near(double actual,double expected,double tolerance,const char* message){if(!std::isfinite(actual)||std::fabs(actual-expected)>tolerance)throw std::runtime_error(std::string(message)+": "+std::to_string(actual)+" versus "+std::to_string(expected));}
template<class F> double simpson(F f,double a,double b){return (b-a)*(f(a)+4*f((a+b)/2)+f(b))/6;}
template<class F> double integrate(F f,double a,double b,double whole,double tol,unsigned depth=0){const double m=(a+b)/2,l=simpson(f,a,m),r=simpson(f,m,b),error=l+r-whole;if(depth==23||std::fabs(error)<15*tol)return l+r+error/15;return integrate(f,a,m,l,tol/2,depth+1)+integrate(f,m,b,r,tol/2,depth+1);}
template<class F> double integrate(F f,double a,double b){return integrate(f,a,b,simpson(f,a,b),1e-10);}
// Direct Bernstein/power formulas, independent of de Casteljau evaluation.
LatheSample reference(const LatheProfile& p,double u){unsigned i=0;while(i<5&&u>p.input.heights[i+1])++i;const double width=p.input.heights[i+1]-p.input.heights[i],t=(u-p.input.heights[i])/width,v=1-t;const auto& a=p.segments[i].controls;const double r=v*v*v*a[0][0]+3*t*v*v*a[1][0]+3*t*t*v*a[2][0]+t*t*t*a[3][0];const double d=3*(v*v*(a[1][0]-a[0][0])+2*v*t*(a[2][0]-a[1][0])+t*t*(a[3][0]-a[2][0]))/(width*p.input.height);return {r,p.input.hollow&&u>=p.input.floor?std::max(0.0,r-p.input.wall):0,d};}
LatheMeasure independent(const LatheProfile& p){LatheMeasure m;std::array<double,8> boundaries{};std::copy(p.input.heights.begin(),p.input.heights.end(),boundaries.begin());boundaries[7]=p.input.floor;std::sort(boundaries.begin(),boundaries.end());for(unsigned i=1;i<8;++i){const double a=boundaries[i-1],b=boundaries[i];if(b<=a)continue;const auto sample=[&](double u){return reference(p,std::clamp(u,a+1e-13,b-1e-13));};m.volume+=pi*p.input.height*integrate([&](double u){const auto q=sample(u);return q.radius*q.radius-q.inner*q.inner;},a,b);m.outerArea+=2*pi*p.input.height*integrate([&](double u){const auto q=sample(u);return q.radius*std::hypot(1,q.slope);},a,b);m.innerArea+=2*pi*p.input.height*integrate([&](double u){const auto q=sample(u);return q.inner*std::hypot(1,q.slope);},a,b);}return m;}
void kernel(){
  for(double radius:{0.0,.1,1.0,1.5})for(double height:{1.0,3.0,4.0})for(bool hollow:{false,true}){
    LatheInput input;input.radii.fill(radius);input.height=height;input.wall=.2;input.floor=.2;input.hollow=hollow;const auto p=prepareLathe(input);const auto m=measureLathe(p);const double inner=hollow?std::max(0.0,radius-.2):0;
    near(m.volume,pi*height*(radius*radius-inner*inner*.8),1e-12,"cylinder material volume");near(m.outerArea,2*pi*radius*height,1e-12,"cylinder outer lateral area");near(m.innerArea,2*pi*inner*height*.8,1e-12,"cylinder inner lateral area");near(m.closureArea,2*pi*radius*radius,1e-12,"cylinder closures");near(approximateLatheArea(p,4),m.area,1e-12,"constant profile exact frustums");const auto half=measureLathe(p,.5);near(half.volume,m.volume/2,1e-12,"half revolution volume");near(half.cutArea,2*height*(radius-.8*inner),1e-12,"radial cut areas");near(measureLathe(p,0).area,0,0,"zero revolution area");++certificates;
  }
  for(double bottom:{0.0,.5}){LatheInput input;input.hollow=false;input.height=3;for(unsigned i=0;i<7;++i)input.radii[i]=bottom+input.heights[i];const auto p=prepareLathe(input);const auto m=measureLathe(p);const double top=bottom+1;near(m.volume,pi*(bottom*bottom+bottom*top+top*top),1e-12,"cone / frustum volume");near(m.outerArea,pi*(bottom+top)*std::sqrt(10.0),1e-12,"cone / frustum lateral area");for(unsigned i=0;i<=100;++i){const auto s=sampleLathe(p,i/100.0);near(s.radius,bottom+i/100.0,1e-14,"linear profile preserved");near(s.slope,1.0/3,1e-14,"linear slope preserved");}++certificates;}
  for(unsigned test=0;test<12;++test){LatheInput input;input.hollow=test%2;input.floor=.04+.06*test;for(unsigned i=0;i<7;++i)input.radii[i]=.75+.75*std::sin((test+2)*(i+1)*.713);const auto p=prepareLathe(input);const auto truth=independent(p),actual=measureLathe(p);near(actual.volume,truth.volume,2e-8,"independent Simpson volume");near(actual.outerArea,truth.outerArea,2e-8,"independent outer area");near(actual.innerArea,truth.innerArea,2e-8,"independent inner area");
    for(unsigned i=0;i<=120;++i){const double u=i/120.0;const auto a=sampleLathe(p,u),b=reference(p,u);near(a.radius,b.radius,1e-14,"Bernstein profile evaluation");near(a.slope,b.slope,1e-12,"profile slope");unsigned segment=0;while(segment<5&&u>input.heights[segment+1])++segment;require(a.radius>=std::min(input.radii[segment],input.radii[segment+1])-1e-12&&a.radius<=std::max(input.radii[segment],input.radii[segment+1])+1e-12,"monotone shape preservation");++certificates;}
    for(unsigned i=1;i<6;++i){const auto a=sampleBezier(p.segments[i-1],1),b=sampleBezier(p.segments[i],0);near(a.first[0]/(input.heights[i]-input.heights[i-1]),b.first[0]/(input.heights[i+1]-input.heights[i]),1e-12,"continuous profile slope");}
    for(unsigned j=1;j<10;++j){const double r=j*p.maximumRadius/10;const auto shell=latheShell(p,r);double sum=0;for(unsigned k=0;k<shell.count;++k){const auto interval=shell.spans[k];require(interval.to>interval.from&&interval.from>=0&&interval.to<=1,"shell interval range");if(k)require(interval.from>shell.spans[k-1].to,"shell intervals overlap");sum+=(interval.to-interval.from)*input.height;for(unsigned q=1;q<8;++q){const auto point=reference(p,interval.from+(interval.to-interval.from)*q/8);require(r<=point.radius+1e-10&&r>=point.inner-1e-10,"shell crosses air");}}
      near(sum,shell.height,1e-13,"shell interval sum");unsigned hit=0;constexpr unsigned samples=4000;for(unsigned k=0;k<samples;++k){const auto q=reference(p,(k+.5)/samples);hit+=r<=q.radius&&r>=q.inner;}near(shell.height,input.height*hit/samples,input.height*14/samples,"independent occupancy grid");++certificates;
    }
  }
  LatheInput input;input.radii={1,.1,1,.1,1,.1,1};input.hollow=false;require(latheShell(prepareLathe(input),.5).count==4,"disconnected shell intervals");input.heights[3]=input.heights[2];bool rejected=false;try{(void)prepareLathe(input);}catch(const std::invalid_argument&){rejected=true;}require(rejected,"unordered heights accepted");input=LatheInput{};input.radii[0]=std::numeric_limits<double>::quiet_NaN();rejected=false;try{(void)prepareLathe(input);}catch(const std::invalid_argument&){rejected=true;}require(rejected,"nonfinite radius accepted");
}
void action(MathObjects& m,MathAction a){const auto r=m.dispatch(a);if(!r.accepted)throw std::runtime_error(std::string(r.reason));}
void set(MathObjects& m,MathParameter p,double v){action(m,{MathActionKind::SetParameter,{},p,v});}
void level(MathObjects& m,unsigned l){action(m,{MathActionKind::SetLevel,{},{},static_cast<double>(l)});}
void preset(MathObjects& m,unsigned p){action(m,{MathActionKind::ObjectPreset,{},{},0,p});}
double metric(const MathObjects& m,std::string_view name){for(unsigned i=0;i<m.snapshot().metricCount;++i)if(m.snapshot().metrics[i].label==name)return m.snapshot().metrics[i].value;throw std::runtime_error("missing metric "+std::string(name));}
void checked(MathObjects& m,bool solved){action(m,{MathActionKind::Check});if((m.snapshot().feedback==MathFeedback::Solved)!=solved)throw std::runtime_error("challenge level "+std::to_string(m.snapshot().level)+": "+std::string(m.snapshot().feedbackText));}
void reject(MathObjects& m,MathAction a){const auto revision=m.snapshot().revision;const auto indices=m.snapshot().solid.indexCount;const auto feedback=m.snapshot().feedback;std::array<double,static_cast<unsigned>(MathParameter::Count)> values{};for(auto p:mathParameterSpecs())values[static_cast<unsigned>(p.id)]=m.parameter(p.id);require(!m.dispatch(a).accepted,"invalid action accepted");require(m.snapshot().revision==revision&&m.snapshot().solid.indexCount==indices&&m.snapshot().feedback==feedback,"rejection mutated snapshot");for(auto p:mathParameterSpecs())near(m.parameter(p.id),values[static_cast<unsigned>(p.id)],0,"rejection mutated parameter");}
double meshVolume(const MathTriangleSurface& m){double result=0;for(unsigned i=0;i<m.indexCount;i+=3){const auto a=m.vertices[m.indices[i]].position,b=m.vertices[m.indices[i+1]].position,c=m.vertices[m.indices[i+2]].position;result+=(static_cast<double>(a.x)*(b.y*c.z-b.z*c.y)+static_cast<double>(a.y)*(b.z*c.x-b.x*c.z)+static_cast<double>(a.z)*(b.x*c.y-b.y*c.x))/6;}return result;}
void inspect(const MathObjects& m,MathObjectScene& scene){const auto& s=m.snapshot();const auto& f=scene.publish(s,{0,0,900,650});++meshes;maxVertices=std::max(maxVertices,f.vertices.size());maxIndices=std::max(maxIndices,f.indices.size());require(!f.vertices.empty()&&f.vertices.size()<=kSceneVertexCapacity&&f.indices.size()<=kSceneIndexCapacity,"scene capacity");require(iggy3d::isFinite(f.clipFromWorld),"finite camera");std::set<unsigned> ids;unsigned covered=0;for(const auto& d:f.draws){require(d.firstIndex==covered&&d.indexCount%3==0&&ids.insert(d.objectId.value).second,"draw ownership");covered+=d.indexCount;}require(covered==f.indices.size(),"index ownership");for(auto i:f.indices)require(i<f.vertices.size(),"scene index range");for(const auto& v:f.vertices){for(auto x:v.position)require(std::isfinite(x),"finite vertex");for(auto x:v.color)require(std::isfinite(x)&&x>=0&&x<=1,"finite colour");}for(unsigned i=0;i<s.metricCount;++i)require(std::isfinite(s.metrics[i].value),"finite metric");for(unsigned i=0;i<s.plotCount;++i)for(unsigned j=0;j<s.plots[i].seriesCount;++j)for(unsigned k=0;k<s.plots[i].series[j].count;++k){const auto p=s.plots[i].series[j].points[k];require(std::isfinite(p.x)&&std::isfinite(p.y),"finite plot");}for(unsigned i=0;i<s.solid.vertexCount;++i)near(iggy3d::length(s.solid.vertices[i].normal),1,3e-7,"unit solid normal");for(unsigned i=0;i<s.solid.indexCount;++i)require(s.solid.indices[i]<s.solid.vertexCount,"solid index range");require(meshVolume(s.solid)>=-1e-5,"negative oriented material volume");}
void geometry(){LatheInput input;input.radii.fill(1);input.height=3;input.wall=.2;input.floor=.2;const auto p=prepareLathe(input);MathTriangleSurface mesh;
  for(double turn:{0.0,1.0/360,.25,.5,1.0})for(double cut:{0.0,.25,.75}){buildLatheSurface(p,{turn,cut},mesh);const double alpha=2*pi*turn*(1-cut),factor=alpha>0?32*std::sin(alpha/32)/(2*pi):0;near(meshVolume(mesh),measureLathe(p).volume*factor,3e-6,"closed cylindrical material mesh volume");for(unsigned i=0;i<mesh.vertexCount;++i)near(iggy3d::length(mesh.vertices[i].normal),1,2e-7,"cylinder normals");++certificates;}
  for(bool shells:{false,true})for(unsigned n:{4U,16U,32U})for(unsigned i=0;i<n;++i){buildLatheElement(p,{1,0},n,shells,i,mesh);near(meshVolume(mesh),approximateLatheVolume(p,n,shells).elements[i].volume*(32*std::sin(2*pi/32)/(2*pi)),2e-6,"highlighted volume equals its table element");++certificates;}
}
void model(){MathObjects m;MathObjectScene scene;action(m,{MathActionKind::Select,MathObjectKind::Lathe});require(mathObjectSpecs().size()==static_cast<unsigned>(MathObjectKind::Count)&&mathLessons(MathObjectKind::Lathe).size()==4,"lathe registration");
  for(unsigned l=0;l<4;++l){level(m,l);for(unsigned p=0;p<4;++p){const auto rev=m.snapshot().revision;preset(m,p);require(m.snapshot().revision==rev+1,"preset must be atomic");const auto& expected=mathObjectPresets(MathObjectKind::Lathe,l)[p];for(unsigned j=0;j<expected.count;++j)near(m.parameter(expected.parameters[j]),expected.values[j],0,"preset values");require(m.snapshot().curve.count==7&&m.snapshot().curve.selectionParameter==MathParameter::LatheControl,"typed profile handles");inspect(m,scene);if(l==2)for(double method:{0.0,1.0}){set(m,MathParameter::LatheMethod,method);set(m,MathParameter::LatheSlices,32);for(double u:{0.0,.25,.5,.75,1.0}){set(m,MathParameter::LatheProbe,u);inspect(m,scene);double sum=0;for(unsigned i=0;i<m.snapshot().table.rowCount;++i)sum+=m.snapshot().table.values[i][3];near(sum,metric(m,"Midpoint volume"),1e-12,"all elements in table");}}
      if(l==3){set(m,MathParameter::LatheGuides,0);const auto area=metric(m,"Boundary area reference");for(double cut:{0.0,25.0,75.0}){set(m,MathParameter::LatheCut,cut);near(metric(m,"Boundary area reference"),area,0,"view cut changed physical area");inspect(m,scene);require(!m.snapshot().curve.active&&m.snapshot().partCount==0,"shape only guides hidden");}}
    }}
  level(m,0);preset(m,0);checked(m,true);for(unsigned i=0;i<7;++i)set(m,static_cast<MathParameter>(static_cast<unsigned>(MathParameter::LatheR0)+i),1);checked(m,false);preset(m,0);reject(m,{MathActionKind::SetParameter,{},MathParameter::LatheH3,.1});set(m,MathParameter::LatheH3,.65);require(m.snapshot().feedback==MathFeedback::None,"editing clears feedback");level(m,3);near(m.parameter(MathParameter::LatheH3),.65,1e-14,"profile retained across layers");
  level(m,1);preset(m,0);checked(m,false);set(m,MathParameter::LatheTurn,180);checked(m,true);set(m,MathParameter::LatheTurn,0);action(m,{MathActionKind::TogglePlayback});action(m,{MathActionKind::AdvanceTime,{},{},2});near(m.parameter(MathParameter::LatheTurn),180,0,"four second revolution");set(m,MathParameter::LatheControl,4);require(!m.snapshot().playing,"edit pauses playback");action(m,{MathActionKind::TogglePlayback});action(m,{MathActionKind::AdvanceTime,{},{},3});near(m.parameter(MathParameter::LatheTurn),360,0,"revolution clamp");require(!m.snapshot().playing,"revolution stops");reject(m,{MathActionKind::TogglePlayback});
  level(m,2);preset(m,3);checked(m,false);set(m,MathParameter::LatheSlices,32);checked(m,true);level(m,3);preset(m,3);checked(m,false);set(m,MathParameter::LatheSlices,32);checked(m,true);set(m,MathParameter::LatheProbe,1);near(metric(m,"Normal defined"),0,0,"axis probe undefined");checked(m,false);
  for(unsigned l=0;l<4;++l){level(m,l);preset(m,0);for(unsigned pass=0;pass<2;++pass)for(const auto& p:mathParameterSpecs())if(m.parameterAvailable(p.id)){double value=pass?p.maximum:p.minimum;if(p.id>=MathParameter::LatheH1&&p.id<=MathParameter::LatheH5){const auto i=static_cast<unsigned>(p.id);value=pass?(p.id==MathParameter::LatheH5?1:m.parameter(static_cast<MathParameter>(i+1)))-.04:(p.id==MathParameter::LatheH1?0:m.parameter(static_cast<MathParameter>(i-1)))+.04;}set(m,p.id,value);inspect(m,scene);reject(m,{MathActionKind::SetParameter,{},p.id,std::numeric_limits<double>::quiet_NaN()});reject(m,{MathActionKind::SetParameter,{},p.id,p.maximum+1});}reject(m,{MathActionKind::ObjectPreset,{},{},0,4});}
  level(m,3);preset(m,0);for(unsigned i=0;i<7;++i)set(m,static_cast<MathParameter>(static_cast<unsigned>(MathParameter::LatheR0)+i),0);inspect(m,scene);require(m.snapshot().solid.indexCount==0&&m.snapshot().curve.active,"zero profile remains editable");checked(m,false);action(m,{MathActionKind::Reset});near(m.parameter(MathParameter::LatheR2),1.15,0,"reset profile");
  // Alternating peaks force many cavity crossings and disconnected shell spans.
  for(unsigned i=0;i<7;++i)set(m,static_cast<MathParameter>(static_cast<unsigned>(MathParameter::LatheR0)+i),i%2?.01:1.5);for(double cut:{0.0,75.0})for(double probe:{0.0,.135,.5,.875,1.0}){set(m,MathParameter::LatheCut,cut);set(m,MathParameter::LatheProbe,probe);inspect(m,scene);}level(m,2);set(m,MathParameter::LatheMethod,1);for(double probe:{.005,.25,.5,.75,.995}){set(m,MathParameter::LatheProbe,probe);inspect(m,scene);}
  level(m,3);preset(m,0);const auto start=std::chrono::steady_clock::now();for(unsigned i=0;i<20;++i)set(m,MathParameter::LatheProbe,i/20.0);std::printf("Lathe area-layer rebuild mean: %.3f ms.\n",std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count()/20);
  action(m,{MathActionKind::Select,MathObjectKind::Curve});require(m.snapshot().solid.indexCount==0&&m.snapshot().curve.count==4,"solid and picker state leak to another object");inspect(m,scene);
}
}
int main(){try{kernel();geometry();model();std::printf("Lathe passed: %u numerical certificates, %u CPU meshes; max %zu vertices / %zu indices. No host, fonts or images.\n",certificates,meshes,maxVertices,maxIndices);return 0;}catch(const std::exception& e){std::fprintf(stderr,"Lathe tests failed: %s\n",e.what());return 1;}}
