# Exercise real startup failures before any graphics resources are requested.
file(REMOVE_RECURSE "${TEST_DIR}")
file(MAKE_DIRECTORY "${TEST_DIR}/elsewhere")
file(COPY "${SOURCE_CONTENT}/cards" "${SOURCE_CONTENT}/packs" DESTINATION "${TEST_DIR}")
set(pack "${TEST_DIR}/packs/gallery_foundation.json")
set(card "${TEST_DIR}/cards/foundation_substitution_integral_6x.json")
file(READ "${pack}" original_pack)
file(READ "${card}" original_card)

function(reject path source field reason)
  execute_process(COMMAND "${GALLERY}" --start-mode substitution_chain
    --content-pack "${path}" --offscreen --frames 1
    WORKING_DIRECTORY "${TEST_DIR}/elsewhere" TIMEOUT 10
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  string(FIND "${error}" "${source}:${field}:" location)
  string(FIND "${error}" "${reason}" detail)
  if(NOT status EQUAL 1 OR location LESS 0 OR detail LESS 0)
    message(FATAL_ERROR "Expected content rejection at ${source}:${field} (${reason}); status=${status}\n${output}${error}")
  endif()
endfunction()

reject("${TEST_DIR}/missing.json" "${TEST_DIR}/missing.json" "<root>" "cannot open file")
string(JSON changed SET "${original_pack}" schema_version 99)
file(WRITE "${pack}" "${changed}")
reject("${pack}" "${pack}" "/schema_version" "unsupported schema version")
string(JSON changed REMOVE "${original_pack}" decks substitution_chain)
file(WRITE "${pack}" "${changed}")
reject("${pack}" "${pack}" "/decks/substitution_chain" "missing deck")
string(JSON changed SET "${original_pack}" questions 4 "\"../cards/missing.json\"")
file(WRITE "${pack}" "${changed}")
reject("${pack}" "${TEST_DIR}/cards/missing.json" "<root>" "cannot open file")
file(WRITE "${pack}" "${original_pack}")
string(JSON changed SET "${original_card}" schema_version 99)
file(WRITE "${card}" "${changed}")
reject("${pack}" "${card}" "/schema_version" "unsupported schema version")
string(JSON changed SET "${original_card}" steps 0 accepted_option_ids 0 999)
file(WRITE "${card}" "${changed}")
reject("${pack}" "${card}" "/steps/0/accepted_option_ids/0" "unknown accepted option ID")
file(WRITE "${card}" "{")
reject("${pack}" "${card}" "<root>" "parse_error")
message(STATUS "Gallery content startup rejection checks passed")
