#include "app/iggy3d/ProductControllerActionMap.hpp"

#include <algorithm>
#include <array>
#include <cstddef>

namespace iggy3d {
namespace {

constexpr std::array<std::string_view, 23> kControllerControlNames{
    "none",
    "left_stick_up",
    "left_stick_down",
    "left_stick_left",
    "left_stick_right",
    "right_stick_up",
    "right_stick_down",
    "right_stick_left",
    "right_stick_right",
    "dpad_up",
    "dpad_down",
    "dpad_left",
    "dpad_right",
    "south_button",
    "east_button",
    "west_button",
    "north_button",
    "left_shoulder",
    "right_shoulder",
    "left_trigger",
    "right_trigger",
    "left_stick_press",
    "right_stick_press",
};

constexpr std::array<bool, 23> kModeChordComponentControls{
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    true,
    true,
    true,
};

constexpr std::array kActionMapRows{
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::LeftStickUp,
                                  InputAction::PlayerMoveY,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::LeftStickDown,
                                  InputAction::PlayerMoveY,
                                  -1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::LeftStickLeft,
                                  InputAction::PlayerMoveX,
                                  -1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::LeftStickRight,
                                  InputAction::PlayerMoveX,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::RightStickUp,
                                  InputAction::PlayerLookY,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::RightStickDown,
                                  InputAction::PlayerLookY,
                                  -1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::RightStickLeft,
                                  InputAction::PlayerLookX,
                                  -1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::RightStickRight,
                                  InputAction::PlayerLookX,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::SouthButton,
                                  InputAction::PlayerInteract,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::LeftStickUp,
                                  InputAction::EditorNudgeZ,
                                  -1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::LeftStickDown,
                                  InputAction::EditorNudgeZ,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::LeftStickLeft,
                                  InputAction::EditorNudgeX,
                                  -1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::LeftStickRight,
                                  InputAction::EditorNudgeX,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::DpadUp,
                                  InputAction::EditorNudgeZ,
                                  -1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::DpadDown,
                                  InputAction::EditorNudgeZ,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::DpadLeft,
                                  InputAction::EditorNudgeX,
                                  -1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::DpadRight,
                                  InputAction::EditorNudgeX,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::SouthButton,
                                  InputAction::EditorConfirmPreview,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::EastButton,
                                  InputAction::EditorCancelPreview,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::WestButton,
                                  InputAction::EditorPreviewPlacement,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::NorthButton,
                                  InputAction::EditorRotateWallDirection,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::LeftShoulder,
                                  InputAction::EditorPreviousTool,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::Gameplay,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::RightShoulder,
                                  InputAction::EditorNextTool,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::LeftStickUp,
                                  InputAction::EditorNudgeZ,
                                  -1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::LeftStickDown,
                                  InputAction::EditorNudgeZ,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::LeftStickLeft,
                                  InputAction::EditorNudgeX,
                                  -1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::LeftStickRight,
                                  InputAction::EditorNudgeX,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::DpadUp,
                                  InputAction::EditorNudgeZ,
                                  -1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::DpadDown,
                                  InputAction::EditorNudgeZ,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::DpadLeft,
                                  InputAction::EditorNudgeX,
                                  -1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::DpadRight,
                                  InputAction::EditorNudgeX,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::SouthButton,
                                  InputAction::EditorConfirmPreview,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::EastButton,
                                  InputAction::EditorCancelPreview,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::WestButton,
                                  InputAction::EditorPreviewPlacement,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::NorthButton,
                                  InputAction::EditorRotateWallDirection,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::LeftShoulder,
                                  InputAction::EditorPreviousTool,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Player,
                                  ProductControllerControl::RightShoulder,
                                  InputAction::EditorNextTool,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::LeftStickUp,
                                  InputAction::EditorNudgeZ,
                                  -1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::LeftStickDown,
                                  InputAction::EditorNudgeZ,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::LeftStickLeft,
                                  InputAction::EditorNudgeX,
                                  -1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::LeftStickRight,
                                  InputAction::EditorNudgeX,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::DpadUp,
                                  InputAction::EditorNudgeZ,
                                  -1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::DpadDown,
                                  InputAction::EditorNudgeZ,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::DpadLeft,
                                  InputAction::EditorNudgeX,
                                  -1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::DpadRight,
                                  InputAction::EditorNudgeX,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::SouthButton,
                                  InputAction::EditorConfirmPreview,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::EastButton,
                                  InputAction::EditorCancelPreview,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::WestButton,
                                  InputAction::EditorPreviewPlacement,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::NorthButton,
                                  InputAction::EditorRotateWallDirection,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::LeftShoulder,
                                  InputAction::EditorPreviousTool,
                                  1.0F},
    ProductControllerActionMapRow{ProductInputSurface::RoomEditor,
                                  ProductInteractionMode::Creative,
                                  ProductControllerControl::RightShoulder,
                                  InputAction::EditorNextTool,
                                  1.0F},
};

}  // namespace

std::string_view productControllerControlName(ProductControllerControl control) {
  return kControllerControlNames[static_cast<std::size_t>(control)];
}

bool productControllerControlIsModeChordComponent(
    ProductControllerControl control) {
  return kModeChordComponentControls[static_cast<std::size_t>(control)];
}

std::span<const ProductControllerActionMapRow> productControllerActionMapRows() {
  return kActionMapRows;
}

ProductControllerActionMapResult mapProductControllerAction(
    ProductControllerActionMapRequest request) {
  ProductControllerActionMapResult result;
  const bool chordComponent =
      productControllerControlIsModeChordComponent(request.control);
  if (chordComponent) {  // branch-gate: BG-1057
    result.status = "controller_action_chord_reserved";
    result.reasonCode = result.status;
    return result;
  }

  const auto rows = productControllerActionMapRows();
  const auto row = std::find_if(
      rows.begin(),
      rows.end(),
      [request](const ProductControllerActionMapRow& candidate) {
        return candidate.surface == request.surface &&
               candidate.interactionMode == request.interactionMode &&
               candidate.control == request.control;
      });
  if (row == rows.end()) {  // branch-gate: BG-1057
    return result;
  }

  result.mapped = true;
  result.action = row->action;
  result.actionValue = row->actionValue;
  result.status = "controller_action_mapped";
  result.reasonCode = result.status;
  return result;
}

}  // namespace iggy3d
