#pragma once

#include <cstdint>

#include "app/frontend/FrontendState.hpp"
#include "app/frontend/SettingsMenu.hpp"
#include "app/input/InputAction.hpp"
#include "app/frontend/MenuInput.hpp"
#include "app/iggy3d/world/DefaultWorldTemplate.hpp"
#include "app/iggy3d/gameplay/ActiveRoomCollision.hpp"
#include "app/iggy3d/gameplay/ActiveRoomState.hpp"
#include "app/iggy3d/gameplay/MovementTuning.hpp"
#include "app/iggy3d/Options.hpp"
#include "app/iggy3d/input/InteractionMode.hpp"
#include "app/iggy3d/room_editor/Cursor.hpp"
#include "app/iggy3d/room_editor/Preview.hpp"
#include "app/iggy3d/room_editor/EditingState.hpp"
#include "app/iggy3d/view/ViewportState.hpp"
#include "app/iggy3d/save/SaveBridge.hpp"
#include "render/RenderDiagnostics.hpp"

namespace iggy3d {

struct ProductAppWindowState {
  bool requested = false;
  bool sdlAvailable = false;
  bool created = false;
  bool drawable = false;
  bool openingMenuVisible = false;
  bool menuTextDrawn = false;
  bool selectedRowDrawn = false;
  bool mouseMenuSelectUsed = false;
  bool gamepadAvailable = false;
  bool gamepadMenuSelectUsed = false;
  std::string gamepadName = "unavailable";
  std::string gamepadMapping = "unavailable";
  ProductInteractionMode interactionMode = ProductInteractionMode::Player;
  bool mapMakerActive = false;
  std::string mapMakerStatus = "map_maker_inactive";
  std::string mapMakerReasonCode = "map_maker_inactive";
  bool mapMakerGridVisible = false;
  std::string mapMakerGridStatus = "map_maker_grid_disabled";
  std::string mapMakerGridReasonCode = "map_maker_grid_disabled";
  float mapMakerGridPitchMeters = 1.0F;
  float mapMakerGridMajorStepMeters = 5.0F;
  float mapMakerGridPlaneY = 0.0F;
  std::uint64_t mapMakerGridLayerCount = 0;
  std::uint64_t mapMakerGridDotCount = 0;
  std::uint64_t mapMakerGridMajorDotCount = 0;
  bool interactionModeHudVisible = false;
  std::string interactionModeHudStatus = "interaction_mode_hud_hidden";
  std::string interactionModeHudReasonCode = "interaction_mode_hud_hidden";
  std::string interactionModeHudMode = "player";
  std::string interactionModeHudLabel = "player";
  bool topDownMapVisible = false;
  std::string topDownMapPurpose = "hidden";
  std::string topDownMapSize = "hidden";
  std::string topDownMapStatus = "top_down_map_hidden";
  std::string topDownMapReasonCode = "top_down_map_hidden";
  std::uint64_t topDownMapItemCount = 0;
  bool mouseCaptureRequested = false;
  bool mouseCaptureActive = false;
  std::string mouseCaptureStatus = "mouse_capture_not_requested";
  std::string mouseCaptureReasonCode = "mouse_capture_gameplay_inactive";
  std::string mouseCaptureMode = "none";
  std::string mouseCaptureInputOwner = "none";
  bool controllerModeToggleRequested = false;
  bool controllerModeToggleAccepted = false;
  std::string controllerModeToggleStatus = "interaction_mode_toggle_not_requested";
  std::string controllerModeToggleReasonCode = "interaction_mode_toggle_not_requested";
  std::string controllerModeToggleSurface = "none";
  bool controllerActionMapped = false;
  std::string controllerActionStatus = "controller_action_not_requested";
  std::string controllerActionReasonCode = "controller_action_not_requested";
  std::string controllerActionControl = "none";
  std::string controllerActionMode = "player";
  std::string controllerActionSurface = "none";
  std::string controllerActionInputAction = "none";
  FrontendSettingsTab selectedSettingsTab = FrontendSettingsTab::None;
  bool runtimeSessionCreated = false;
  bool gameplayActive = false;
  std::string launchAction = "none";
  std::string launchStatus = "not_requested";
  std::string packageLoadStatus = "not_requested";
  std::string worldSetupTitle = "New World";
  std::string worldSetupStatus = "not_requested";
  std::string worldSetupDungeonTitle = "none";
  std::uint64_t worldSetupDungeonIndex = 0;
  std::uint64_t worldSetupDungeonCount = 0;
  bool worldSetupAsciiRoomEnabled = false;
  bool worldSetupAsciiRoomTextPresent = false;
  std::string worldSetupAsciiRoomId = "world_setup_room";
  std::string worldSetupAsciiRoomSourceName = "world_setup_ascii_room.iggyroom.txt";
  bool worldSetupDungeonDraftEditMode = false;
  bool worldSetupDungeonDraftModified = false;
  std::uint64_t worldSetupDungeonDraftCursorRow = 0;
  std::uint64_t worldSetupDungeonDraftCursorColumn = 0;
  std::string worldSetupDungeonDraftStatus = "not_requested";
  std::string worldSetupDungeonDraftReasonCode = "not_requested";
  std::string worldSetupDungeonDraftSelectedGlyph = ".";
  std::string worldSetupDungeonDraftLastGlyph = "none";
  std::string worldCreationStatus = "not_requested";
  std::string worldCreationReasonCode = "not_requested";
  std::string worldCreationWorldId = "none";
  std::string worldCreationWorldTitle = "none";
  bool worldCreationAsciiRoomRequested = false;
  std::string worldCreationAsciiRoomId = "none";
  std::string worldCreationAsciiRoomSourceName = "none";
  bool worldCreationInitialSaveRequested = false;
  bool worldCreationInitialSaveWritten = false;
  std::string worldCreationInitialSaveId = "none";
  std::string worldCreationInitialSaveTitle = "none";
  std::string worldCreationRouteAfterCreate = "world_setup";
  std::string asciiRoomDraftText;
  std::string asciiRoomDraftRoomId = "ascii_preview";
  std::string asciiRoomDraftSourceName = "automation_ascii_room";
  std::string asciiRoomPreviewStatus = "not_requested";
  std::string asciiRoomPreviewReasonCode = "not_requested";
  std::string asciiRoomPreviewFailedStage = "not_started";
  std::string asciiRoomPreviewRoomId = "none";
  std::string asciiRoomPreviewSourceName = "none";
  bool asciiRoomPreviewReady = false;
  std::uint64_t asciiRoomPreviewWidth = 0;
  std::uint64_t asciiRoomPreviewHeight = 0;
  std::uint64_t asciiRoomPreviewFloorCount = 0;
  std::uint64_t asciiRoomPreviewWallCount = 0;
  std::uint64_t asciiRoomPreviewObjectCount = 0;
  std::uint64_t asciiRoomPreviewMarkerCount = 0;
  std::uint64_t asciiRoomPreviewElevatedFloorCount = 0;
  std::uint64_t asciiRoomPreviewRampCount = 0;
  std::uint64_t asciiRoomPreviewBlockedSlopeCount = 0;
  std::uint64_t asciiRoomPreviewStaticMeshCount = 0;
  std::uint64_t asciiRoomPreviewAnchorCount = 0;
  std::uint64_t asciiRoomPreviewSpatialSurfaceCount = 0;
  bool asciiRoomPreviewAssetTextWritten = false;
  std::uint64_t asciiRoomPreviewAssetTextBytes = 0;
  std::string asciiRoomActivationStatus = "not_requested";
  std::string asciiRoomActivationReasonCode = "not_requested";
  std::string asciiRoomActivationRoomId = "none";
  std::string asciiRoomActivationPackageId = "none";
  std::string asciiRoomActivationScenarioId = "none";
  bool asciiRoomActivationSessionCreated = false;
  bool asciiRoomActivationPlayerSpawned = false;
  std::uint64_t asciiRoomActivationPlayerCount = 0;
  std::uint64_t asciiRoomActivationEntityCount = 0;
  std::uint64_t asciiRoomActivationNpcCount = 0;
  std::uint64_t asciiRoomActivationPickupCount = 0;
  std::uint64_t asciiRoomActivationDoorCount = 0;
  std::uint64_t asciiRoomActivationMarkerEntityCount = 0;
  std::uint64_t asciiRoomActivationObjectiveCount = 0;
  std::uint64_t asciiRoomActivationWallCount = 0;
  std::uint64_t asciiRoomActivationMarkerCount = 0;
  std::uint64_t asciiRoomActivationRuntimeHash = 0;
  ProductRoomEditingState roomEditing;
  std::string roomEditingLastOperation = "none";
  std::string roomEditingLastOperationStatus = "not_requested";
  std::string roomEditingLastOperationReasonCode = "not_requested";
  std::string roomEditingLastInputSource = "none";
  bool roomEditingLastOperationAccepted = false;
  std::string roomEditingLastPrimitiveId = "none";
  bool roomEditorCursorReady = false;
  ProductRoomEditorCursorState roomEditorCursor;
  std::string roomEditorStatus = "not_requested";
  std::string roomEditorReasonCode = "not_requested";
  std::string roomEditorLastOperation = "none";
  bool roomEditorLastOperationAccepted = false;
  std::string roomEditorLastPrimitiveId = "none";
  bool roomEditorOverlayVisible = false;
  std::string roomEditorOverlayStatus = "room_editor_overlay_not_ready";
  std::string roomEditorOverlayReasonCode = "room_editor_overlay_not_ready";
  std::uint64_t roomEditorOverlayItemCount = 0;
  float roomEditorOverlayWorldX = 0.0F;
  float roomEditorOverlayWorldY = 0.0F;
  float roomEditorOverlayWorldZ = 0.0F;
  bool roomEditorPreviewActive = false;
  ProductRoomEditorPlacementPreviewResult roomEditorPlacementPreview;
  bool roomEditorPreviewVisible = false;
  std::string roomEditorPreviewStatus = "room_editor_preview_not_requested";
  std::string roomEditorPreviewReasonCode = "room_editor_preview_not_requested";
  std::string roomEditorPreviewCandidateId = "none";
  std::string roomEditorPreviewTool = "floor";
  std::int32_t roomEditorPreviewGridX = 0;
  std::int32_t roomEditorPreviewGridZ = 0;
  std::uint64_t roomEditorPreviewBeforeDrawCount = 0;
  std::uint64_t roomEditorPreviewAfterDrawCount = 0;
  std::int64_t roomEditorPreviewAvoidedDrawCountDelta = 0;
  std::uint64_t roomEditorPreviewBeforeTriangleCount = 0;
  std::uint64_t roomEditorPreviewAfterTriangleCount = 0;
  std::int64_t roomEditorPreviewAvoidedTriangleCountDelta = 0;
  std::int64_t roomEditorPreviewOptimizedDrawDelta = 0;
  std::int64_t roomEditorPreviewOptimizedTriangleDelta = 0;
  bool roomEditorHudVisible = false;
  std::string roomEditorHudStatus = "room_editor_hud_not_ready";
  std::string roomEditorHudReasonCode = "room_editor_hud_not_ready";
  std::string roomEditorHudTool = "floor";
  std::string roomEditorHudWallDirection = "up";
  std::int32_t roomEditorHudGridX = 0;
  std::int32_t roomEditorHudGridZ = 0;
  std::string roomEditorHudLastOperation = "none";
  bool roomEditorHudLastOperationAccepted = false;
  std::string roomEditorHudLastPrimitiveId = "none";
  bool roomEditorHudPreviewActive = false;
  std::string roomEditorHudPreviewStatus = "room_editor_preview_not_requested";
  std::string roomEditorHudPreviewCandidateId = "none";
  std::int64_t roomEditorHudPreviewOptimizedDrawDelta = 0;
  std::int64_t roomEditorHudPreviewOptimizedTriangleDelta = 0;
  std::uint64_t roomEditorHudLineCount = 0;
  ProductActiveRoomState activeRoom;
  ProductActiveRoomCollisionState activeRoomCollision;
  std::string productSaveStatus = "not_requested";
  std::string productSaveReasonCode = "not_requested";
  std::string productSaveDurableReason = "not_requested";
  std::string productSaveSource = "none";
  std::string productSaveSaveId = "none";
  bool productSaveSessionSaved = false;
  std::string activeProductSaveId = "none";
  std::string productSaveLoadStatus = "not_requested";
  std::string productSaveLoadReasonCode = "not_requested";
  std::string productSaveLoadSaveId = "none";
  std::string productSaveLoadSource = "none";
  std::string productSaveLoadSelectedId = "none";
  bool productSaveLoadSelectedEnabled = false;
  bool productSaveLoadAuthoredRoomPresent = false;
  std::string productSaveLoadAuthoredRoomId = "none";
  std::uint64_t productSaveLoadAuthoredFloorCount = 0;
  std::uint64_t productSaveLoadAuthoredWallCount = 0;
  std::uint64_t productSaveLoadAuthoredObjectCount = 0;
  std::uint64_t productSaveLoadAuthoredMarkerCount = 0;
  std::string savedMarkerBindStatus = "not_requested";
  std::string savedMarkerBindReasonCode = "not_requested";
  bool savedMarkerBindRequested = false;
  bool savedMarkerBindSessionReplaced = false;
  std::string savedMarkerBindRoomId = "none";
  std::uint64_t savedMarkerBindMarkerCount = 0;
  std::uint64_t savedMarkerBindSeedEntityCount = 0;
  std::uint64_t savedMarkerBindAddedEntityCount = 0;
  std::uint64_t savedMarkerBindExistingEntityCount = 0;
  std::uint64_t savedMarkerBindAddedObjectiveCount = 0;
  std::uint64_t savedMarkerBindExistingObjectiveCount = 0;
  std::uint64_t savedMarkerBindAddedCombatantCount = 0;
  std::uint64_t savedMarkerBindExistingCombatantCount = 0;
  std::uint64_t savedMarkerBindPickupCount = 0;
  std::uint64_t savedMarkerBindDoorCount = 0;
  std::uint64_t savedMarkerBindMarkerEntityCount = 0;
  std::uint64_t savedMarkerBindNpcCount = 0;
  std::uint64_t savedMarkerBindPreviousHash = 0;
  std::uint64_t savedMarkerBindBoundHash = 0;
  std::string selectedProductSaveId = "none";
  bool selectedProductSaveEnabled = false;
  std::string selectedProductSaveStatus = "none";
  bool saveDeleteConfirmationOpen = false;
  std::string saveDeleteCandidateId = "none";
  bool saveDeleteCandidateEnabled = false;
  std::string saveDeleteStatus = "not_requested";
  std::string saveDeleteReasonCode = "not_requested";
  std::string saveDeleteType = "none";
  bool saveDeleteRecoverable = false;
  bool saveDeleteExecuted = false;
  bool deletedSaveBrowserOpen = false;
  std::uint64_t deletedSaveCount = 0;
  std::uint64_t deletedCompatibleSaveCount = 0;
  std::string deletedSelectedSaveId = "none";
  bool deletedSelectedSaveEnabled = false;
  std::string deletedSelectedSaveStatus = "none";
  std::string saveRecoverStatus = "not_requested";
  std::string saveRecoverReasonCode = "not_requested";
  bool saveRecoverExecuted = false;
  std::string saveRecoverSaveId = "none";
  bool saveRecoverSnapshotRecovered = false;
  bool saveRecoverSnapshotMissing = false;
  std::uint64_t productSaveLoadPreviousHash = 0;
  std::uint64_t productSaveLoadLoadedHash = 0;
  bool productSaveLoadSessionLoaded = false;
  std::uint64_t runtimeStateHash = 0;
  ProductViewportState viewport;
  std::uint64_t sceneItemCount = 0;
  std::uint64_t debugItemCount = 0;
  bool npcBehaviorDebugHudVisible = false;
  bool npcBehaviorDebugHudDebugAvailable = false;
  std::uint64_t npcBehaviorDebugHudLineCount = 0;
  std::string npcBehaviorDebugHudStatus = "not_requested";
  std::string npcBehaviorDebugHudReasonCode = "not_requested";
  bool npcBehaviorDebugHudHasUnresolvedProfile = false;
  bool physicsDebugHudVisible = false;
  bool physicsDebugHudDebugAvailable = false;
  std::uint64_t physicsDebugHudLineCount = 0;
  std::string physicsDebugHudStatus = "not_requested";
  std::string physicsDebugHudReasonCode = "not_requested";
  bool physicsDebugHudHasWarnings = false;
  bool positionHudVisible = false;
  bool positionHudDebugAvailable = false;
  std::uint64_t positionHudLineCount = 0;
  std::string positionHudStatus = "not_requested";
  std::string positionHudReasonCode = "not_requested";
  bool positionHudPlayerPositionAvailable = false;
  float positionHudWorldX = 0.0F;
  float positionHudWorldY = 0.0F;
  float positionHudWorldZ = 0.0F;
  std::int64_t positionHudGridX = 0;
  std::int64_t positionHudGridY = 0;
  std::int64_t positionHudGridZ = 0;
  std::int64_t positionHudLayerIndex = 0;
  std::string positionHudFacing = "north";
  float positionHudYawDegrees = 0.0F;
  float positionHudPitchDegrees = 0.0F;
  bool playerVisible = false;
  bool roomVisible = false;
  bool objectiveVisible = false;
  bool rendererMutatedRuntime = false;
  bool scriptedGameplaySmoke = false;
  bool gameplayInputUsed = false;
  bool gameplayCommandSubmitted = false;
  bool gameplayCommandAccepted = false;
  bool gameplayTickAdvanced = false;
  bool playerPositionChanged = false;
  bool gameplayMovementAttempted = false;
  bool gameplayMovementBlocked = false;
  std::string gameplayMovementStatus = "not_requested";
  bool gameplayMovementDebugAvailable = false;
  std::string gameplayMovementReasonCode = "not_requested";
  std::string gameplayMovementBlockedReason = "none";
  std::string gameplayMovementHitSurfaceId = "none";
  bool gameplayMovementGroundSnapApplied = false;
  bool gameplayMovementClamped = false;
  bool gameplayMovementSlid = false;
  std::uint64_t gameplayMovementCollisionSweepCount = 0;
  std::string gameplayMovementPolicyBand = "none";
  std::string gameplayMovementSlopeTravelDirection = "stationary";
  float gameplayMovementSlopeAngleDegrees = 0.0F;
  float gameplayMovementSpeedMultiplier = 1.0F;
  float gameplayMovementStartX = 0.0F;
  float gameplayMovementStartY = 0.0F;
  float gameplayMovementStartZ = 0.0F;
  float gameplayMovementFinalX = 0.0F;
  float gameplayMovementFinalY = 0.0F;
  float gameplayMovementFinalZ = 0.0F;
  float gameplayMovementHorizontalDistanceMeters = 0.0F;
  float gameplayMovementVerticalDeltaMeters = 0.0F;
  float gameplayMovementGradePercent = 0.0F;
  std::string gameplayMovementProfile =
      std::string{kProductGameplayMovementTuning.walkProfile};
  float gameplayMovementMaxSpeedMetersPerSecond =
      kProductGameplayMovementTuning.walkSpeedMetersPerSecond;
  ProductGameplayMovementTuning gameplayMovementTuning =
      productGameplayMovementTuning();
  ProductGameplayMovementTuningField gameplayMovementTuningSelectedField =
      ProductGameplayMovementTuningField::WalkSpeed;
  bool gameplayMovementTuningVisible = false;
  std::string gameplayMovementTuningStatus = "movement_tuning_ready";
  std::string gameplayMovementTuningReasonCode = "movement_tuning_ready";
  bool gameplayJumpRequested = false;
  bool gameplayJumpAccepted = false;
  bool gameplayJumpActive = false;
  std::string gameplayJumpStatus = "not_requested";
  std::string gameplayJumpReasonCode = "not_requested";
  float gameplayJumpVelocityMetersPerSecond = 0.0F;
  float gameplayJumpGroundY = 0.0F;
  float gameplayJumpStartY = 0.0F;
  float gameplayJumpFinalY = 0.0F;
  float gameplayJumpHeightMeters = 0.0F;
  bool gameplayResetTriggered = false;
  std::string gameplayResetStatus = "not_requested";
  std::string gameplayResetReasonCode = "not_requested";
  std::string gameplayResetSpawnAnchorId = "none";
  std::string gameplayResetSourceAnchorId = "none";
  float gameplayResetStartY = 0.0F;
  float gameplayResetFinalY = 0.0F;
  bool gameplayTraversalRequested = false;
  bool gameplayTraversalConsumed = false;
  bool gameplayTraversalAccepted = false;
  bool gameplayTraversalFallbackJumpAllowed = false;
  std::string gameplayTraversalStatus = "not_requested";
  std::string gameplayTraversalReasonCode = "not_requested";
  std::string gameplayTraversalMechanic = "none";
  std::string gameplayTraversalSlotId = "none";
  std::string gameplayTraversalTargetId = "none";
  std::string gameplayTraversalLandingSurfaceId = "none";
  float gameplayTraversalStartX = 0.0F;
  float gameplayTraversalStartY = 0.0F;
  float gameplayTraversalStartZ = 0.0F;
  float gameplayTraversalFinalX = 0.0F;
  float gameplayTraversalFinalY = 0.0F;
  float gameplayTraversalFinalZ = 0.0F;
  bool gameplayDashRequested = false;
  bool gameplayDashAccepted = false;
  std::string gameplayDashStatus = "not_requested";
  std::string gameplayDashReasonCode = "not_requested";
  float gameplayDashSpeedMetersPerSecond = 0.0F;
  float gameplayDashDistanceMeters = 0.0F;
  float gameplayDashCooldownRemainingSeconds = 0.0F;
  float gameplayDashDirectionX = 0.0F;
  float gameplayDashDirectionZ = 0.0F;
  bool gameplayCollisionSurfacesUsed = false;
  std::uint64_t gameplayCollisionSurfaceCount = 0;
  std::string gameplayTickReasonCode = "not_requested";
  bool physicsMovementPlannerEnabled = false;
  bool physicsMovementPlannerRequested = false;
  bool physicsMovementPlannerUsed = false;
  std::string physicsMovementPlannerStatus = "physics_movement_planner_disabled";
  std::string physicsMovementPlannerReasonCode = "physics_movement_planner_disabled";
  bool targetDiscovered = false;
  std::string gameplayTargetStatus = "not_requested";
  std::string gameplayTargetAction = "none";
  std::uint64_t gameplayTargetEntityId = 0;
  std::string gameplayTargetStableName = "none";
  std::string gameplayTargetKind = "none";
  float gameplayTargetDistanceMeters = 0.0F;
  bool gameplayTargetSupportsCommand = false;
  std::string gameplayOutcomeStatus = "not_requested";
  bool gameplayOutcomeTargetActiveAfter = false;
  bool gameplayOutcomeInventoryChanged = false;
  std::string gameplayOutcomeItemId = "none";
  std::uint64_t gameplayOutcomeItemCount = 0;
  bool gameplayOutcomeObjectiveChanged = false;
  std::uint64_t gameplayOutcomeEventCount = 0;
  std::string sessionOutcome = "None";
  bool gameplayTapeRequested = false;
  bool gameplayTapeLoaded = false;
  std::string gameplayTapePath = "none";
  std::string gameplayTapeStatus = "not_requested";
  std::string gameplayTapeReasonCode = "not_requested";
  std::uint64_t gameplayTapeLineCount = 0;
  std::uint64_t gameplayTapeStepCount = 0;
  std::uint64_t gameplayTapeExecutedStepCount = 0;
  std::uint64_t gameplayTapeExpectedRejectedStepCount = 0;
  std::uint64_t gameplayTapeExpectedBlockedStepCount = 0;
  std::string gameplayTapeFailedStep = "none";
  std::uint64_t gameplayTapeFailedSourceLine = 0;
  std::string gameplayTapeFailedAction = "none";
  std::string gameplayTapeFailedTarget = "none";
  std::string gameplayTapeFailedRejection = "none";
  std::string gameplayTapeFailedMovementBlock = "none";
  std::string gameplayTapeLastAction = "none";
  std::string gameplayTapeLastTarget = "none";
  std::string gameplayTapeLastMovementBlock = "none";
  bool gameplayTapeKeyCollected = false;
  bool gameplayTapeSecretDoorOpened = false;
  bool gameplayTapeTreasureCollected = false;
  bool gameplayTapeNpcTargetable = false;
  bool gameplayTapeNpcDefeated = false;
  bool gameplayTapeExitObjectiveComplete = false;
  bool gameplayTapeLoopComplete = false;
  bool gameplayTapeAiCommandLogged = false;
  bool gameplayTapeAiAttackLogged = false;
  bool gameplayTapeAiWaitLogged = false;
  bool gameplayTapeAiPlayerDamaged = false;
  std::int32_t gameplayTapeAiPlayerHpBefore = 0;
  std::int32_t gameplayTapeAiPlayerHpAfter = 0;
  std::string gameplayTapeAiActorId = "none";
  std::string gameplayTapeAiTargetId = "none";
  std::string gameplayTapeAiBehavior = "none";
  std::string gameplayTapeAiIntent = "none";
  bool interactionExecuted = false;
  bool attackExecuted = false;
  std::string productTransitionLastAction = "none";
  std::string productTransitionStatus = "not_requested";
  bool productTransitionReturnedToGameplay = false;
  bool productTransitionReturnedToTitle = false;
  bool productTransitionSessionPreserved = false;
  std::string gameplayInputSource = "none";
  std::string gameplayCommandKind = "none";
  std::string gameplayCommandStatus = "not_requested";
  std::string gameplayReachGate = "not_attempted";
  std::string gameplayLastRejection = "none";
  MenuOwner inputOwner = MenuOwner::None;
  InputAction lastInputAction = InputAction::None;
  bool lastInputAccepted = false;
  bool gameplayInputSuppressed = false;
  bool automationControlRequested = false;
  bool automationControlLoaded = false;
  std::string automationControlPath;
  std::string automationControlStatus = "not_requested";
  std::string automationControlScope = "none";
  std::uint64_t automationControlLineCount = 0;
  std::uint64_t automationControlAppliedCount = 0;
  std::string automationControlLastKey = "none";
  std::string automationControlLastAction = "none";
  MenuOwner automationControlLastOwner = MenuOwner::None;
  std::string automationControlLastResult = "none";
  bool productVulkanRendererRequested = false;
  bool productVulkanRendererCreated = false;
  bool productVulkanRendererReady = false;
  bool productVulkanSurfaceCreated = false;
  bool productVulkanSwapchainReady = false;
  bool productVulkanFrameSubmitted = false;
  std::uint64_t productVulkanFrameSubmittedCount = 0;
  std::string productVulkanStatus = "not_requested";
  std::string productVulkanReasonCode = "not_requested";
  std::string productVulkanRenderingPath = "none";
  std::string productVulkanRecordMode = "none";
  bool productVulkanMenuRequested = false;
  bool productVulkanMenuVisible = false;
  std::string productVulkanMenuStatus = "vulkan_menu_not_requested";
  std::string productVulkanMenuReasonCode = "vulkan_menu_not_requested";
  std::string productVulkanMenuSurface = "none";
  bool productVulkanMenuUiReady = false;
  bool productVulkanMenuUiPartial = false;
  std::string productVulkanMenuUiStatus = "product_vulkan_menu_ui_not_requested";
  std::string productVulkanMenuUiReasonCode = "product_vulkan_menu_ui_not_requested";
  std::uint64_t productVulkanMenuUiPrimitiveCount = 0;
  std::uint64_t productVulkanMenuUiTextCount = 0;
  std::uint64_t productVulkanMenuUiRectCount = 0;
  std::uint64_t productVulkanMenuUiRowCount = 0;
  std::string productVulkanMenuUiSelectedAction = "none";
  std::uint64_t framesPresented = 0;
  std::uint64_t eventPollCount = 0;
  std::uint64_t menuRowCount = 0;
  std::string status = "window_not_requested";
};

RenderReceipt buildProductAppReceipt(const ProductAppOptions& options,
                                     const ProductWorldTemplate& world,
                                     const FrontendState& frontend,
                                     const FrontendSettings& settings,
                                     const ProductAppWindowState& window,
                                     const ProductSaveBridgeResult& saves);

void recordProductPhysicsMovementPlannerTickProof(
    ProductAppWindowState& window,
    bool requested,
    bool collisionSurfacesAvailable,
    bool movementPhysicsStatsAvailable);

}  // namespace iggy3d
