#include "app/input/InputDeviceEvent.hpp"

namespace iggy3d {

std::string_view neutralInputName(NeutralInput input) {
  switch (input) {
    case NeutralInput::None:
      return "none";
    case NeutralInput::KeyW:
      return "key.w";
    case NeutralInput::KeyA:
      return "key.a";
    case NeutralInput::KeyS:
      return "key.s";
    case NeutralInput::KeyD:
      return "key.d";
    case NeutralInput::KeyUp:
      return "key.up";
    case NeutralInput::KeyDown:
      return "key.down";
    case NeutralInput::KeyLeft:
      return "key.left";
    case NeutralInput::KeyRight:
      return "key.right";
    case NeutralInput::KeyEnter:
      return "key.enter";
    case NeutralInput::KeySpace:
      return "key.space";
    case NeutralInput::KeyEscape:
      return "key.escape";
    case NeutralInput::KeyTab:
      return "key.tab";
    case NeutralInput::KeyShiftTab:
      return "key.shift_tab";
    case NeutralInput::KeyF1:
      return "key.f1";
    case NeutralInput::KeyF2:
      return "key.f2";
    case NeutralInput::KeyF3:
      return "key.f3";
    case NeutralInput::KeyE:
      return "key.e";
    case NeutralInput::KeyR:
      return "key.r";
    case NeutralInput::MouseLeft:
      return "mouse.left";
    case NeutralInput::MouseDeltaX:
      return "mouse.delta_x";
    case NeutralInput::MouseDeltaY:
      return "mouse.delta_y";
    case NeutralInput::ButtonSouth:
      return "button.south";
    case NeutralInput::ButtonEast:
      return "button.east";
    case NeutralInput::ButtonNorth:
      return "button.north";
    case NeutralInput::ButtonWest:
      return "button.west";
    case NeutralInput::DpadUp:
      return "dpad.up";
    case NeutralInput::DpadDown:
      return "dpad.down";
    case NeutralInput::DpadLeft:
      return "dpad.left";
    case NeutralInput::DpadRight:
      return "dpad.right";
    case NeutralInput::Start:
      return "button.start";
    case NeutralInput::Back:
      return "button.back";
    case NeutralInput::StartBackChord:
      return "button.start_back_chord";
    case NeutralInput::LeftStickX:
      return "axis.left_x";
    case NeutralInput::LeftStickY:
      return "axis.left_y";
    case NeutralInput::RightStickX:
      return "axis.right_x";
    case NeutralInput::RightStickY:
      return "axis.right_y";
    case NeutralInput::LeftTrigger:
      return "trigger.left";
    case NeutralInput::RightTrigger:
      return "trigger.right";
    case NeutralInput::AutomationMenuUp:
      return "automation.menu.up";
    case NeutralInput::AutomationMenuDown:
      return "automation.menu.down";
    case NeutralInput::AutomationMenuConfirm:
      return "automation.menu.confirm";
    case NeutralInput::AutomationMenuBack:
      return "automation.menu.back";
    case NeutralInput::AutomationPause:
      return "automation.system.pause";
    case NeutralInput::AutomationDevTools:
      return "automation.dev.toggle";
    case NeutralInput::AutomationHardQuit:
      return "automation.system.quit_chord";
    case NeutralInput::AutomationInteract:
      return "automation.game.interact";
    case NeutralInput::AutomationAttack:
      return "automation.game.attack";
    case NeutralInput::AutomationRetryOrReset:
      return "automation.game.retry_or_reset";
  }
  return "none";
}

}  // namespace iggy3d
