#include "Textbook.hpp"
namespace paths {
const std::array<const char*,7>& textbookParts() {
  static const std::array<const char*,7> parts{
    "I. Foundations and Algebra", "II. Trigonometry and Geometry", "III. Calculus",
    "IV. Linear Algebra", "V. Discrete Mathematics and Structures",
    "VI. Probability and Statistics", "VII. Numerical Methods"};
  return parts;
}
const std::array<BookSection,7>& matrixChapter() {
  static const std::array<BookSection,7> sections{{
    {"matrix.entries","1.1 Reading a matrix",
     "Read an entry, state the dimensions, and distinguish data from unknowns.",
     {"A matrix is an ordered rectangular array. In a matrix with m rows and n columns, a(i,j) means the entry in row i and column j. The order matters: a 2 by 3 matrix and a 3 by 2 matrix describe different arrangements.",
      "The numbers inside a supplied matrix are givens. Row and column labels are indices. Its dimensions describe its shape. An unknown vector x in A x = b has n entries, while b has m entries, so each row of A contributes one equation.",
      "An augmented matrix [A | b] explicitly attaches the right-hand side to A. A final column is not automatically a right-hand side. Card 004 supplies ordinary matrices; all their columns belong to A."},
     {{"Entry","The scalar at a specified row and column."},{"Dimensions","The number of rows followed by the number of columns: m by n."},{"Augmented matrix","The matrix A and an explicitly declared right-hand side b displayed as [A | b]."}},
     "Select an entry in the figure and read its indices. Hover to inspect its value. Count the rows and columns before performing any operation.",
     "A small reading example",
     {"Let A = [[2, -1, 4], [0, 3, 5]]. It has two rows and three columns.",
      "a(1,2) = -1, whereas a(2,1) = 0. Exchanging indices changes which entry you read.",
      "In A x = b, x has three entries and b has two. The first equation is 2*x1 - x2 + 4*x3 = b1."},
     "Use card 004 as a reading drill: state each part's dimensions and identify a supplied entry. The next section develops its row-reduction task.",
     "Reading companion to card 004, Meckes & Meckes, section 1.2, exercise 1.2.3. The example here is separately authored.",4},
    {"matrix.rref","1.2 Row operations and RREF",
     "Transform a matrix using reversible row operations and recognize reduced row echelon form.",
     {},
     {{"Elementary row operation","A reversible row swap, nonzero row scaling, or addition of a multiple of another row.","rref.operations"},
      {"Row equivalence","A relationship between matrices connected by a finite sequence of elementary row operations.","rref.equivalence"},
      {"Row echelon form","A matrix with zero rows last and successive nonzero rows starting strictly farther right.","rref.echelon"},
      {"Pivot","The leading nonzero entry of a nonzero row in echelon form.","rref.echelon"},
      {"RREF","Echelon form with leading 1s that are the only nonzero entries in their columns.","rref.reduced"}},
     "","",{},
     "Card 004 asks for the RREF of six printed matrices. Work one part at a time. Check tests row equivalence and the RREF conditions; it does not record completion on the source page.",
     "Card 004: Meckes & Meckes, Linear Algebra, chapter 1, exercise 1.2.3. All six printed parts are available. The numbered lesson, example and practice questions here are separately authored.",4,rrefLesson()},
    {"matrix.partial-pivoting","1.3 Systems and partial pivoting",
     "Keep the right-hand side synchronized and choose a usable pivot from the active column.",
     {"To reduce A x = b, carry b through every row operation. Swapping rows of A without swapping the matching entries of b changes the equations instead of merely rearranging them. The same rule applies to scaling and row addition.",
      "Partial pivoting chooses an entry of largest magnitude in the active column, among the current row and those below it, and moves that row into the pivot position. An all-zero active column cannot supply a pivot. Floating-point code needs an explicit small-pivot policy.",
      "The routine on card 031 is named Forward-Substitution in its source, but it converts a general system to an upper-triangular one. It normalizes each pivot row, then eliminates below it. Solving the resulting triangular system by back substitution is a subsequent operation."},
     {{"Right-hand side","The vector b in A x = b; it follows every row operation."},{"Partial pivoting","Choosing a largest-magnitude available entry in the active column and swapping its row into place."},{"Upper-triangular system","A system whose coefficient matrix has zero entries below its diagonal."}},
     "The chosen system starts with a zero first pivot. Perform one pivot and compare Given b with Working rhs to see the same row swap and scaling.",
     "Moving the right-hand side with the rows",
     {"Take A = [[0, 2], [1, 3]] and b = [4, 7]. Swap both rows of the augmented system.",
      "Now A = [[1, 3], [0, 2]] and b = [7, 4]. Divide the second row, including its right-hand side, by 2.",
      "The triangular equations are x1 + 3*x2 = 7 and x2 = 2. Back substitution gives x1 = 1."},
     "Card 031 asks you to modify an algorithm. The board supplies chosen systems with planted x=(1,...,1), so you can test the behavior. A numerical pass is not a review of your source-code argument.",
     "Card 031: Solomon, Numerical Algorithms, chapter 3, exercise 3.4 and Figure 3.1. Board matrices are chosen examples.",31},
    {"matrix.lu","1.4 LU and leading blocks",
     "Read elimination as a factorization and understand why leading blocks matter.",
     {"In unpivoted elimination, subtract multiples of a pivot row from rows below it without normalizing the pivot row. U records the resulting upper-triangular matrix. L records the multipliers below its diagonal and has 1s on its diagonal, giving A = L U.",
      "For a nonsingular square matrix, an unpivoted LU factorization with unit-lower L exists exactly when every leading principal block is nonsingular. A leading principal block is the top-left k by k corner. A nonsingular full matrix can still have a singular first corner.",
      "The unit diagonal fixes the scaling of L. If A=L1*U1=L2*U2, then inverse(L1)*L2=U1*inverse(U2). This matrix is both unit lower triangular and upper triangular, so it is the identity. This explains uniqueness under the stated hypotheses; a few successful numerical cases alone cannot establish the theorem."},
     {{"LU factorization","Writing A as L U, with L unit lower triangular and U upper triangular."},{"Leading principal block","The top-left k by k corner, using the same initial row and column indices."},{"Unit lower triangular","A matrix with zeros above its diagonal and 1s on the diagonal."}},
     "Select a leading block. Compare the dominant example with the invertible zero-first-pivot example. After beginning work, Check reports the selected block's determinant.",
     "Recording an elimination multiplier",
     {"Let A = [[2, 1], [4, 3]]. The multiplier for removing the 4 is 4/2 = 2.",
      "Subtract twice row 1 from row 2. Then U = [[2, 1], [0, 1]] and L = [[1, 0], [2, 1]]. Multiplying L U recovers A.",
      "The leading determinants are 2 and 2, both nonzero. This verifies one instance; the general equivalence needs an argument for every leading block."},
     "Card 018 asks for both directions of an equivalence and uniqueness. Use the board to test examples and find the point of breakdown, then supply the general reasoning separately.",
     "Card 018: Trefethen & Bau, Numerical Linear Algebra, Lecture 20, exercise 20.1. The unit-lower convention is explicit.",18},
    {"matrix.permutations","1.5 Recording permutations",
     "Track row swaps without losing the factorization identity.",
     {"A permutation matrix rearranges rows when it multiplies A on the left. In the convention used by card 044, the factorization is P A = L U. The familiar name LUP does not specify the multiplication order.",
      "Each new row swap must update P. If earlier pivot columns already have multipliers stored in L, the affected entries in those earlier columns must also swap. Recording swaps only in U can leave a plausible-looking pair of triangular factors that reconstructs the wrong matrix.",
      "At completion, verify both the shapes of the factors and their product. L must have a unit diagonal and zeros above it; U must have zeros below its diagonal; P must describe a permutation. The numerical residual measures how closely L U matches P A."},
     {{"Permutation matrix","An identity matrix with rearranged rows; exactly one 1 occurs in each row and column."},{"PA = LU","The convention in which row-permuted A equals the product of the triangular factors."},{"Factorization residual","A numerical measure of the difference between the reconstructed product and the stated matrix."}},
     "Work both printed parts. Part (b) exercises a later row swap, where previously recorded multipliers matter. The completed trace exposes P, L and U in separate tabs.",
     "A row swap before elimination",
     {"Let A = [[0, 1], [2, 3]]. Choose P = [[0, 1], [1, 0]] to swap its rows.",
      "Then P A = [[2, 3], [0, 1]], already upper triangular. Set L to the identity and U to this result.",
      "L U = P A. Writing A = L U P would describe a different identity and fails for these factors."},
     "Find factors for the two printed matrices on card 044. The board checks the stated identity. The source asks for two methods; this board currently supplies an invariant check.",
     "Card 044: Meckes & Meckes, chapter 2, exercise 2.4.12. Its current Notation fold explicitly states PA=LU.",44},
    {"matrix.bands","1.6 Banded matrices and sparsity",
     "Separate prescribed zeros from small numbers and trace the reach of an elimination step.",
     {"A matrix with half-bandwidth p has a(i,j)=0 whenever |i-j|>p. This prescribes a band around the diagonal. A structural zero follows from that pattern; a small floating-point entry is merely a measured value unless more has been established.",
      "Under the leading-block hypothesis, unpivoted elimination preserves the corresponding lower band in L and upper band in U. At pivot k, only rows within p places below k need updating, and the pivot row reaches no farther than p places to the right. Tracing these supports explains why no farther entries are created.",
      "Pivoting can change sparsity behavior, so keep the unpivoted assumption in the statement. Chosen diagonally dominant examples make the required leading blocks nonsingular. Try several sizes and bands, while keeping the proof of the general support claim separate from those measurements."},
     {{"Half-bandwidth","The allowed maximum distance p from the diagonal for a potentially nonzero entry."},{"Structural zero","An entry prescribed to be zero by the mathematical structure."},{"Fill-in","An entry that becomes nonzero during a computation despite starting at zero."}},
     "Change size and half-bandwidth. Dark cells in Given A are prescribed zeros. Complete the trace and compare the bands of L and U.",
     "A tridiagonal example",
     {"For A = [[4, 1, 0], [1, 4, 1], [0, 1, 4]], the half-bandwidth is 1.",
      "The first multiplier is 1/4. The second pivot becomes 15/4, so the next multiplier is 4/15.",
      "U has diagonal [4, 15/4, 56/15] and superdiagonal [1, 1]. L has subdiagonal [1/4, 4/15]. The distant corners remain zero."},
     "Card 001 asks what can be said about the factor patterns for the whole family. Use the board's band check as evidence for chosen examples and explain why the permitted row updates preserve the pattern.",
     "Card 001: Trefethen & Bau, Lecture 20, exercise 20.2, under the condition imported from 20.1.",1},
    {"matrix.schur","1.7 Block elimination",
     "Group entries into blocks and identify the Schur complement left after eliminating one block.",
     {"Partition a square matrix as [[A11, A12], [A21, A22]], with A11 an n by n leading block. Block multiplication follows the same row-by-column rule as scalar multiplication, but the order of matrix factors must be preserved.",
      "When A11 is invertible, eliminating A21 leaves the trailing block S = A22 - A21*inverse(A11)*A12. This is the Schur complement of A11. For computation, solve A11*X=A12 and form S=A22-A21*X, avoiding an explicit inverse.",
      "After n scalar elimination steps, the bottom-right block agrees with this S. The top-left blocks need not look the same: scalar elimination has also changed A11, while the block formula leaves it intact. Compare the trailing blocks when checking the two methods."},
     {{"Block partition","A division of a matrix into rectangular submatrices with compatible dimensions."},{"Schur complement","The remaining block A22 - A21*inverse(A11)*A12 after eliminating A21."},{"Block solve","Solving a matrix equation such as A11*X=A12 for several right-hand sides together."}},
     "Choose a size and block cut n. After n pivots, inspect the Schur block tab. Check compares it with an independently computed block solve.",
     "Eliminating a one by one block",
     {"Take A = [[2, 1], [4, 5]] and choose n=1. Then A11=2, A12=1, A21=4 and A22=5.",
      "Solve 2*X=1, giving X=1/2. The Schur complement is 5 - 4*(1/2) = 3.",
      "Subtract twice row 1 from row 2 to obtain [[2, 1], [0, 3]]. Its trailing entry agrees with the block calculation."},
     "Card 059 asks you to verify the block identity and explain why scalar elimination gives the same trailing block. The board checks numerical agreement; the general block argument remains yours to write.",
     "Card 059: Trefethen & Bau, Lecture 20, exercise 20.3. A11 and every required leading block are assumed nonsingular.",59}
  }};
  return sections;
}
} // namespace paths
