if(NOT DEFINED IGGY3D_INSTALL_HEADLESS_DEMO)
  option(IGGY3D_INSTALL_HEADLESS_DEMO "Install the headless demo binary" ON)
endif()
if(NOT DEFINED IGGY3D_INSTALL_VULKAN_SHADERS)
  option(IGGY3D_INSTALL_VULKAN_SHADERS "Install generated Vulkan shader artifacts" OFF)
endif()
if(NOT DEFINED IGGY3D_INSTALL_RUNTIME_DEPS)
  option(IGGY3D_INSTALL_RUNTIME_DEPS "Install runtime dependency bundles" OFF)
endif()
if(NOT DEFINED IGGY3D_INSTALL_VALIDATION_TOOLS)
  option(IGGY3D_INSTALL_VALIDATION_TOOLS "Install validation tooling" OFF)
endif()

if(TARGET iggy3d_headless_demo AND IGGY3D_INSTALL_HEADLESS_DEMO)
  install(TARGETS iggy3d_headless_demo RUNTIME DESTINATION bin)
endif()

if(TARGET iggy3d_replay_tool AND IGGY3D_INSTALL_HEADLESS_DEMO)
  install(TARGETS iggy3d_replay_tool RUNTIME DESTINATION bin)
endif()

if(IGGY3D_INSTALL_VULKAN_SHADERS AND TARGET iggy3d_vulkan_shaders)
  install(DIRECTORY "${IGGY3D_SHADER_BINARY_ROOT}/" DESTINATION "share/iggy3d/shaders/vulkan")
endif()
