option(IGGY3D_BUILD_TESTS "Build iggy3d tests" ON)
option(IGGY3D_BUILD_TOOLS "Build iggy3d tools" ON)
option(IGGY3D_WARNINGS_AS_ERRORS "Treat iggy3d warnings as errors" OFF)

message(STATUS "IGGY3D_BUILD_TESTS=${IGGY3D_BUILD_TESTS}")
message(STATUS "IGGY3D_BUILD_TOOLS=${IGGY3D_BUILD_TOOLS}")
message(STATUS "IGGY3D_WARNINGS_AS_ERRORS=${IGGY3D_WARNINGS_AS_ERRORS}")
