function(iggy3d_apply_warnings target_name)
  if(NOT TARGET "${target_name}")
    message(FATAL_ERROR "iggy3d_apply_warnings missing target: ${target_name}")
  endif()

  if(MSVC)
    target_compile_options("${target_name}" PRIVATE /W4)
    if(IGGY3D_WARNINGS_AS_ERRORS)
      target_compile_options("${target_name}" PRIVATE /WX)
    endif()
  elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
    target_compile_options("${target_name}" PRIVATE -Wall -Wextra -Wpedantic -Wconversion)
    if(IGGY3D_WARNINGS_AS_ERRORS)
      target_compile_options("${target_name}" PRIVATE -Werror)
    endif()
  else()
    message(STATUS "iggy3d warning policy has no flags for compiler ${CMAKE_CXX_COMPILER_ID}")
  endif()
endfunction()
