set(IGGY3D_HAS_SDL3_TARGET OFF)
set(IGGY3D_HAS_VULKAN_TARGET OFF)
set(IGGY3D_SDL3_TARGET "")
set(IGGY3D_VULKAN_TARGET "")
set(IGGY3D_VULKAN_SDK_ROOT "")
set(IGGY3D_VULKAN_SDK_SOURCE "not_found")
set(IGGY3D_VULKAN_ICD_PATH "")
set(IGGY3D_VULKAN_ICD_FOUND OFF)

if(IGGY3D_BUILD_TOOLS OR IGGY3D_ENABLE_VULKAN_SMOKE)
  if(IGGY3D_USE_SYSTEM_SDL3)
    find_package(SDL3 CONFIG QUIET)
    if(TARGET SDL3::SDL3)
      set(IGGY3D_HAS_SDL3_TARGET ON)
      set(IGGY3D_SDL3_TARGET SDL3::SDL3)
      set(IGGY3D_SDL3_SOURCE "system")
    elseif(TARGET SDL3::SDL3-shared)
      set(IGGY3D_HAS_SDL3_TARGET ON)
      set(IGGY3D_SDL3_TARGET SDL3::SDL3-shared)
      set(IGGY3D_SDL3_SOURCE "system")
    elseif(TARGET SDL3::SDL3-static)
      set(IGGY3D_HAS_SDL3_TARGET ON)
      set(IGGY3D_SDL3_TARGET SDL3::SDL3-static)
      set(IGGY3D_SDL3_SOURCE "system")
    else()
      set(IGGY3D_SDL3_SOURCE "missing")
    endif()
  else()
    set(IGGY3D_SDL3_SOURCE "disabled")
  endif()
else()
  set(IGGY3D_SDL3_SOURCE "disabled")
endif()

if(IGGY3D_BUILD_TOOLS OR IGGY3D_ENABLE_VULKAN OR IGGY3D_ENABLE_VULKAN_SMOKE)
  set(_iggy3d_vulkan_sdk_candidates)
  if(DEFINED ENV{VULKAN_SDK} AND NOT "$ENV{VULKAN_SDK}" STREQUAL "")
    list(APPEND _iggy3d_vulkan_sdk_candidates "$ENV{VULKAN_SDK}")
  endif()
  if(APPLE)
    list(APPEND _iggy3d_vulkan_sdk_candidates "/Users/kogaryu/VulkanSDK")
    file(GLOB _iggy3d_macos_vulkan_sdk_roots
      LIST_DIRECTORIES true
      "/Users/kogaryu/VulkanSDK/*/macOS")
    list(APPEND _iggy3d_vulkan_sdk_candidates ${_iggy3d_macos_vulkan_sdk_roots})
  endif()
  foreach(_iggy3d_sdk_candidate IN LISTS _iggy3d_vulkan_sdk_candidates)
    if(IGGY3D_VULKAN_SDK_ROOT STREQUAL "" AND EXISTS "${_iggy3d_sdk_candidate}")
      get_filename_component(IGGY3D_VULKAN_SDK_ROOT "${_iggy3d_sdk_candidate}" ABSOLUTE)
      if(DEFINED ENV{VULKAN_SDK} AND "${_iggy3d_sdk_candidate}" STREQUAL "$ENV{VULKAN_SDK}")
        set(IGGY3D_VULKAN_SDK_SOURCE "environment")
      else()
        set(IGGY3D_VULKAN_SDK_SOURCE "default_path")
      endif()
    endif()
  endforeach()

  find_package(Vulkan QUIET)
  if(TARGET Vulkan::Vulkan)
    set(IGGY3D_HAS_VULKAN_TARGET ON)
    set(IGGY3D_VULKAN_TARGET Vulkan::Vulkan)
    set(IGGY3D_VULKAN_LOADER "found")
    if(IGGY3D_VULKAN_SDK_ROOT STREQUAL "" AND DEFINED Vulkan_INCLUDE_DIRS)
      foreach(_iggy3d_vulkan_include_dir IN LISTS Vulkan_INCLUDE_DIRS)
        get_filename_component(_iggy3d_vulkan_include_parent
          "${_iggy3d_vulkan_include_dir}/.." ABSOLUTE)
        if(EXISTS "${_iggy3d_vulkan_include_parent}" AND
           IGGY3D_VULKAN_SDK_ROOT STREQUAL "")
          set(IGGY3D_VULKAN_SDK_ROOT "${_iggy3d_vulkan_include_parent}")
          set(IGGY3D_VULKAN_SDK_SOURCE "cmake_discovery")
        endif()
      endforeach()
    endif()
  else()
    set(IGGY3D_VULKAN_LOADER "missing")
  endif()
else()
  set(IGGY3D_VULKAN_LOADER "unavailable")
endif()

set(_iggy3d_icd_candidates)
if(DEFINED ENV{VK_ICD_FILENAMES} AND NOT "$ENV{VK_ICD_FILENAMES}" STREQUAL "")
  string(REPLACE ":" ";" _iggy3d_env_icd_candidates "$ENV{VK_ICD_FILENAMES}")
  list(APPEND _iggy3d_icd_candidates ${_iggy3d_env_icd_candidates})
endif()
if(NOT IGGY3D_VULKAN_SDK_ROOT STREQUAL "")
  list(APPEND _iggy3d_icd_candidates "${IGGY3D_VULKAN_SDK_ROOT}/share/vulkan/icd.d")
endif()
if(APPLE)
  file(GLOB _iggy3d_macos_icd_roots
    LIST_DIRECTORIES true
    "/Users/kogaryu/VulkanSDK/*/macOS/share/vulkan/icd.d")
  list(APPEND _iggy3d_icd_candidates
    ${_iggy3d_macos_icd_roots}
    "/usr/local/share/vulkan/icd.d"
    "/opt/homebrew/share/vulkan/icd.d"
    "/usr/local/etc/vulkan/icd.d"
    "/opt/homebrew/etc/vulkan/icd.d")
endif()
foreach(_iggy3d_icd_candidate IN LISTS _iggy3d_icd_candidates)
  if(IGGY3D_VULKAN_ICD_PATH STREQUAL "" AND EXISTS "${_iggy3d_icd_candidate}")
    if(IS_DIRECTORY "${_iggy3d_icd_candidate}")
      file(GLOB _iggy3d_icd_entries "${_iggy3d_icd_candidate}/*")
      list(LENGTH _iggy3d_icd_entries _iggy3d_icd_entry_count)
      if(_iggy3d_icd_entry_count GREATER 0)
        get_filename_component(IGGY3D_VULKAN_ICD_PATH "${_iggy3d_icd_candidate}" ABSOLUTE)
        set(IGGY3D_VULKAN_ICD_FOUND ON)
      endif()
    else()
      get_filename_component(IGGY3D_VULKAN_ICD_PATH "${_iggy3d_icd_candidate}" ABSOLUTE)
      set(IGGY3D_VULKAN_ICD_FOUND ON)
    endif()
  endif()
endforeach()

set(_iggy3d_glslc_hints)
if(DEFINED ENV{VULKAN_SDK} AND NOT "$ENV{VULKAN_SDK}" STREQUAL "")
  list(APPEND _iggy3d_glslc_hints "$ENV{VULKAN_SDK}/bin")
endif()
if(NOT IGGY3D_VULKAN_SDK_ROOT STREQUAL "")
  list(APPEND _iggy3d_glslc_hints "${IGGY3D_VULKAN_SDK_ROOT}/bin")
endif()
if(APPLE)
  list(APPEND _iggy3d_glslc_hints "/opt/homebrew/bin" "/usr/local/bin")
endif()
unset(IGGY3D_GLSLC_EXE)
unset(IGGY3D_GLSLC_EXE CACHE)
find_program(IGGY3D_GLSLC_EXE NAMES glslc HINTS ${_iggy3d_glslc_hints})

if(IGGY3D_REQUIRE_VULKAN_SMOKE AND IGGY3D_ENABLE_VULKAN_SMOKE)
  if(NOT IGGY3D_HAS_SDL3_TARGET)
    message(FATAL_ERROR "iggy3d Vulkan smoke requires SDL3 but SDL3 was not found")
  endif()
  if(NOT IGGY3D_HAS_VULKAN_TARGET)
    message(FATAL_ERROR "iggy3d Vulkan smoke requires Vulkan but Vulkan was not found")
  endif()
endif()

message(STATUS "iggy3d.sdl3.source=${IGGY3D_SDL3_SOURCE}")
message(STATUS "iggy3d.vulkan.loader=${IGGY3D_VULKAN_LOADER}")
message(STATUS "iggy3d.vulkan.sdk.root=${IGGY3D_VULKAN_SDK_ROOT}")
message(STATUS "iggy3d.vulkan.sdk.source=${IGGY3D_VULKAN_SDK_SOURCE}")
message(STATUS "iggy3d.vulkan.icd.path=${IGGY3D_VULKAN_ICD_PATH}")
message(STATUS "iggy3d.vulkan.icd.found=${IGGY3D_VULKAN_ICD_FOUND}")
message(STATUS "iggy3d.glslc=${IGGY3D_GLSLC_EXE}")
