set(IGGY3D_HAS_SDL3_TARGET OFF)
set(IGGY3D_HAS_VULKAN_TARGET OFF)
set(IGGY3D_SDL3_TARGET "")
set(IGGY3D_VULKAN_TARGET "")

if(IGGY3D_ENABLE_VISUAL_DEMO OR IGGY3D_ENABLE_VULKAN_SMOKE)
  if(IGGY3D_USE_SYSTEM_SDL3)
    find_package(SDL3 CONFIG QUIET)
    if(TARGET SDL3::SDL3)
      set(IGGY3D_HAS_SDL3_TARGET ON)
      set(IGGY3D_SDL3_TARGET SDL3::SDL3)
      set(IGGY3D_SDL3_SOURCE "system")
    elseif(TARGET SDL3::SDL3-shared)
      set(IGGY3D_HAS_SDL3_TARGET ON)
      set(IGGY3D_SDL3_TARGET SDL3::SDL3-shared)
      set(IGGY3D_SDL3_SOURCE "system")
    elseif(TARGET SDL3::SDL3-static)
      set(IGGY3D_HAS_SDL3_TARGET ON)
      set(IGGY3D_SDL3_TARGET SDL3::SDL3-static)
      set(IGGY3D_SDL3_SOURCE "system")
    else()
      set(IGGY3D_SDL3_SOURCE "missing")
    endif()
  else()
    set(IGGY3D_SDL3_SOURCE "disabled")
  endif()
else()
  set(IGGY3D_SDL3_SOURCE "disabled")
endif()

if(IGGY3D_ENABLE_VULKAN OR IGGY3D_ENABLE_VULKAN_SMOKE)
  find_package(Vulkan QUIET)
  if(TARGET Vulkan::Vulkan)
    set(IGGY3D_HAS_VULKAN_TARGET ON)
    set(IGGY3D_VULKAN_TARGET Vulkan::Vulkan)
    set(IGGY3D_VULKAN_LOADER "found")
  else()
    set(IGGY3D_VULKAN_LOADER "missing")
  endif()
else()
  set(IGGY3D_VULKAN_LOADER "unavailable")
endif()

if(IGGY3D_REQUIRE_VULKAN_SMOKE AND IGGY3D_ENABLE_VULKAN_SMOKE)
  if(NOT IGGY3D_HAS_SDL3_TARGET)
    message(FATAL_ERROR "iggy3d Vulkan smoke requires SDL3 but SDL3 was not found")
  endif()
  if(NOT IGGY3D_HAS_VULKAN_TARGET)
    message(FATAL_ERROR "iggy3d Vulkan smoke requires Vulkan but Vulkan was not found")
  endif()
endif()

message(STATUS "iggy3d.sdl3.source=${IGGY3D_SDL3_SOURCE}")
message(STATUS "iggy3d.vulkan.loader=${IGGY3D_VULKAN_LOADER}")
