list(APPEND IGGY_ENGINE_SOURCES
  src/scene/camera/CameraClamp.cpp
  src/scene/camera/CameraFollow.cpp
  src/scene/camera/CameraLookahead.cpp
  src/scene/camera/CameraRig.cpp
  src/scene/camera/CameraShake.cpp
  src/scene/camera/CameraView.cpp
  src/scene/level/LevelBlueprint.cpp
  src/scene/level/LevelCollisionCacheState.cpp
  src/scene/level/LevelCollisionWorldBuilder.cpp
  src/scene/level/LevelDerivedCacheState.cpp
  src/scene/level/LevelNpcUpdateStep.cpp
  src/scene/level/LevelRenderCacheState.cpp
  src/scene/level/LevelRenderFrame2D.cpp
  src/scene/level/LevelRuntimeBuilder.cpp
  src/scene/level/LevelRuntimeUpdate.cpp
  src/scene/level/LevelTileDrawList.cpp
  src/scene/level/LevelTileMap.cpp
  src/scene/level/LevelTileMutation.cpp
  src/scene/level/LevelTileRenderDirtyChunks.cpp
  src/scene/level/LevelTileRenderChunkBuilder.cpp
  src/scene/level/LevelTileRenderChunkCache.cpp
  src/scene/level/LevelTileRenderChunkCacheUpdater.cpp
  src/scene/level/LevelTileRenderChunkCommands.cpp
  src/scene/level/LevelTileRenderChunkVisibility.cpp
  src/scene/level/LevelTileRenderCommands.cpp
  src/scene/level/LevelVisibleTiles.cpp
  src/scene/player/PlayerAgentState.cpp
  src/scene/player/PlayerCommandFramePlanner2D.cpp
  src/scene/player/PlayerCommandPlanner2D.cpp
  src/scene/player/PlayerMovementExecutor2D.cpp
  src/scene/sprite/SpriteRenderCommands2D.cpp
)
