list(APPEND IGGY_ENGINE_SOURCES
  src/runtime/GameplayCommand2D.cpp
  src/runtime/GameplayCommandFrame2DValidator.cpp
  src/runtime/RuntimeSaveChunkArchive.cpp
  src/runtime/RuntimeLevelMutationStep.cpp
  src/runtime/RuntimeCollisionWorldProvider.cpp
  src/runtime/RuntimePlayerCommandExecutionStep.cpp
  src/runtime/RuntimePlayerCommandPlanningStep.cpp
  src/runtime/RuntimePlayerCommandStep.cpp
  src/runtime/RuntimeSessionCommandTick.cpp
  src/runtime/RuntimeSessionCommandTickRunner.cpp
  src/runtime/RuntimeSessionMutationCommandRunner.cpp
  src/runtime/RuntimeSessionMutationCommandStep.cpp
  src/runtime/RuntimeSessionSnapshot.cpp
  src/runtime/RuntimeSessionSnapshotValidator.cpp
  src/runtime/RuntimeSessionState.cpp
  src/runtime/RuntimeSessionTick.cpp
  src/runtime/RuntimeSessionTickRunner.cpp
  src/runtime/RuntimeTick.cpp
  src/runtime/RuntimeTickRunner.cpp
)
