list(APPEND IGGY_ENGINE_SOURCES
  src/scene/ai/AiMap2D.cpp
  src/scene/ai/AiMapQuery2D.cpp
  src/scene/camera/CameraClamp.cpp
  src/scene/camera/CameraFollow.cpp
  src/scene/camera/CameraLookahead.cpp
  src/scene/camera/CameraRig.cpp
  src/scene/camera/CameraShake.cpp
  src/scene/camera/CameraView.cpp
  src/scene/draft/DraftBuildingCompile2D.cpp
  src/scene/draft/DraftCompilePlan2D.cpp
  src/scene/draft/DraftDoorCompile2D.cpp
  src/scene/draft/DraftDocument2D.cpp
  src/scene/draft/DraftLevelGeometryPlan2D.cpp
  src/scene/draft/DraftWallCompile2D.cpp
  src/scene/draft/DraftWallCutCompile2D.cpp
  src/scene/draft/DraftWallDoorAttach2D.cpp
  src/scene/draft/DraftWallDoorMorphPlan2D.cpp
  src/scene/interaction/InteractionEffectApplier2D.cpp
  src/scene/interaction/InteractionEffectCatalog2D.cpp
  src/scene/interaction/InteractionEffect2D.cpp
  src/scene/interaction/InteractionEvent2D.cpp
  src/scene/interaction/InteractionEffectPlanApplier2D.cpp
  src/scene/interaction/InteractionEffectPlan2D.cpp
  src/scene/interaction/InteractionPlan2D.cpp
  src/scene/interaction/InteractionReach2D.cpp
  src/scene/interaction/InteractionTarget2D.cpp
  src/scene/interaction/InteractionTargetQuery2D.cpp
  src/scene/interaction/InteractionTargetToggle2D.cpp
  src/scene/inventory/InventoryAddItem2D.cpp
  src/scene/inventory/InventoryEvent2D.cpp
  src/scene/inventory/InventoryPolicyAddItem2D.cpp
  src/scene/inventory/InventoryStackPolicy2D.cpp
  src/scene/inventory/InventoryState2D.cpp
  src/scene/inventory/ItemDefinition2D.cpp
  src/scene/inventory/LevelItemDropConsume2D.cpp
  src/scene/inventory/LevelItemDrop2D.cpp
  src/scene/inventory/PickupPlan2D.cpp
  src/scene/inventory/PickupPolicyTransfer2D.cpp
  src/scene/inventory/PickupTransfer2D.cpp
  src/scene/level/LevelCombinedDerivedCacheBuilder2D.cpp
  src/scene/level/LevelBlueprint.cpp
  src/scene/level/LevelCollisionCacheState.cpp
  src/scene/level/LevelCollisionSource2D.cpp
  src/scene/level/LevelCollisionSourceWorldBuilder2D.cpp
  src/scene/level/LevelCollisionWorldMerge2D.cpp
  src/scene/level/LevelCollisionWorldBuilder.cpp
  src/scene/level/LevelDerivedCacheState.cpp
  src/scene/level/LevelMutationCacheUpdateStep.cpp
  src/scene/level/LevelNpcUpdateStep.cpp
  src/scene/level/LevelRenderCacheState.cpp
  src/scene/level/LevelRenderFrame2D.cpp
  src/scene/level/LevelRuntimeBuilder.cpp
  src/scene/level/LevelRuntimeUpdate.cpp
  src/scene/level/LevelTileDrawList.cpp
  src/scene/level/LevelTileMap.cpp
  src/scene/level/LevelTileMutation.cpp
  src/scene/level/LevelTileRenderDirtyChunks.cpp
  src/scene/level/LevelTileRenderChunkBuilder.cpp
  src/scene/level/LevelTileRenderChunkCache.cpp
  src/scene/level/LevelTileRenderChunkCacheUpdater.cpp
  src/scene/level/LevelTileRenderChunkCommands.cpp
  src/scene/level/LevelTileRenderChunkVisibility.cpp
  src/scene/level/LevelTileRenderCommands.cpp
  src/scene/level/LevelVisibleTiles.cpp
  src/scene/player/PlayerAgentState.cpp
  src/scene/player/PlayerCommandFramePlanner2D.cpp
  src/scene/player/PlayerCommandPlanner2D.cpp
  src/scene/player/PlayerInputGatedCommandFrameMapper2D.cpp
  src/scene/player/PlayerInputCommandFrameMapper2D.cpp
  src/scene/player/PlayerInputCommandMapper2D.cpp
  src/scene/player/PlayerInputIntentGate2D.cpp
  src/scene/player/PlayerInputIntent2D.cpp
  src/scene/player/PlayerMovementExecutor2D.cpp
  src/scene/sprite/SpriteRenderCommands2D.cpp
  src/scene/ui/UiFeatureContext.cpp
  src/scene/ui/UiInteractionEventPanelModel.cpp
  src/scene/ui/UiRuntimeFrameInspectorModel.cpp
  src/scene/ui/UiRuntimeWorkspaceModel.cpp
  src/scene/ui/UiSettingsState.cpp
  src/scene/ui/UiShellModel.cpp
  src/scene/ui/UiTheme.cpp
  src/scene/ui/UiToolBeltState.cpp
  src/scene/ui/UiToolIntent.cpp
  src/scene/ui/UiToolInventory.cpp
)
