list(APPEND IGGY_ENGINE_SOURCES
  src/runtime/GameplayCommand2D.cpp
  src/runtime/GameplayCommandFrame2DValidator.cpp
  src/runtime/RuntimeAutosaveRotationExecutor.cpp
  src/runtime/RuntimeAutosaveRotationPolicy.cpp
  src/runtime/RuntimeBinaryCodec.cpp
  src/runtime/RuntimeCommandQueue.cpp
  src/runtime/RuntimeGameplaySaveSlotStore.cpp
  src/runtime/RuntimeGameplayOrchestratedFrameRunner.cpp
  src/runtime/RuntimeGameplayOrchestratedFrameRunnerReporter.cpp
  src/runtime/RuntimeGameplayOrchestratedFrameReporter.cpp
  src/runtime/RuntimeGameplayOrchestratedFrameStep.cpp
  src/runtime/RuntimeGameplayAuthoringDiagnostics.cpp
  src/runtime/RuntimeGameplayAuthoringErrorCodes.cpp
  src/runtime/RuntimeGameplayAuthoringPreviewModel.cpp
  src/runtime/RuntimeGameplayProductFrameRequest.cpp
  src/runtime/RuntimeGameplayProductInputContext.cpp
  src/runtime/RuntimeGameplayProductInputAdapter.cpp
  src/runtime/RuntimeGameplayProductLoop.cpp
  src/runtime/RuntimeGameplayProductPlayMode.cpp
  src/runtime/RuntimeGameplayProductPlaySurfaceFrame.cpp
  src/runtime/RuntimeGameplayProductPresentationCamera.cpp
  src/runtime/RuntimeGameplayProductPresentationFrame.cpp
  src/runtime/RuntimeGameplayProductScenarioLoader.cpp
  src/runtime/RuntimeGameplayScenarioAuthoringAdapter.cpp
  src/runtime/RuntimeGameplayAsciiScenarioPacket.cpp
  src/runtime/RuntimeGameplayAsciiScenarioPacketValidator.cpp
  src/runtime/RuntimeGameplayAsciiSourcePlanAdapter.cpp
  src/runtime/RuntimeGameplayAsciiSourcePlan.cpp
  src/runtime/RuntimeGameplayAsciiSourcePlanFinalDebugRows.cpp
  src/runtime/RuntimeGameplayAsciiSourcePlanProfileScenarioConverter.cpp
  src/runtime/RuntimeGameplayAsciiSourcePlanRegionAiMapPromoter.cpp
  src/runtime/RuntimeGameplayAsciiSourcePlanTomlFileReader.cpp
  src/runtime/RuntimeGameplayAsciiSourcePlanTomlReader.cpp
  src/runtime/RuntimeGameplayAsciiSourcePlanValidator.cpp
  src/runtime/RuntimeGameplayTomlScenarioFacade.cpp
  src/runtime/RuntimeGameplayTomlScenarioPackageFacade.cpp
  src/runtime/RuntimeGameplayTomlScenarioPackageReader.cpp
  src/runtime/RuntimeGameplayTomlScenarioSummaryProjection.cpp
  src/runtime/RuntimeGameplayProfileScenarioDefinition.cpp
  src/runtime/RuntimeGameplayProfileScenarioRunner.cpp
  src/runtime/RuntimeGameplayProfileScenarioValidator.cpp
  src/runtime/RuntimeGameplayScenarioDefinition.cpp
  src/runtime/RuntimeGameplayScenarioLedger.cpp
  src/runtime/RuntimeGameplayScenarioReportProjection.cpp
  src/runtime/RuntimeGameplayScenarioRunner.cpp
  src/runtime/RuntimeGameplayScenarioValidator.cpp
  src/runtime/RuntimeGameplayFrameRunner.cpp
  src/runtime/RuntimeGameplayFrameStep.cpp
  src/runtime/RuntimeGameplayFrameReporter.cpp
  src/runtime/RuntimeGameplayState.cpp
  src/runtime/RuntimeGameplaySnapshot.cpp
  src/runtime/RuntimeGameplaySnapshotChunkCodec.cpp
  src/runtime/RuntimeGameplaySnapshotSaveLoad.cpp
  src/runtime/RuntimeGameplaySnapshotValidator.cpp
  src/runtime/RuntimeMutationCommandQueue.cpp
  src/runtime/RuntimeNpcActorMovementFrameStep.cpp
  src/runtime/RuntimeNpcActorMovementPlannedFrameRunner.cpp
  src/runtime/RuntimeNpcActorMovementPlannedFrameStep.cpp
  src/runtime/RuntimeNpcActorMovementRequestPlanStep.cpp
  src/runtime/RuntimeNpcAiControlPlannedFrameStep.cpp
  src/runtime/RuntimeNpcAiProfileControlPlannedFrameStep.cpp
  src/runtime/RuntimeNpcAiProfileMovementPlannedFrameStep.cpp
  src/runtime/RuntimeNpcAiMovementPlannedFrameRunner.cpp
  src/runtime/RuntimeNpcAiMovementPlannedFrameStep.cpp
  src/runtime/RuntimeNpcAiMovementRefreshFrameRunner.cpp
  src/runtime/RuntimeNpcAiMovementRefreshFrameStep.cpp
  src/runtime/RuntimeNpcOrchestrationAggregates.cpp
  src/runtime/RuntimeNpcAiDecisionQueueStep.cpp
  src/runtime/RuntimeNpcAiCommandQueueStep.cpp
  src/runtime/RuntimeNpcAiMovementQueueStep.cpp
  src/runtime/RuntimePlayerNpcAiCommandFrameStep.cpp
  src/runtime/RuntimePlayerNpcAiQueueStep.cpp
  src/runtime/RuntimeInteractionEffectApplyFrameStep.cpp
  src/runtime/RuntimeInteractionEffectApplyStep.cpp
  src/runtime/RuntimeInteractionEffectCommandFrameStep.cpp
  src/runtime/RuntimeInteractionEffectCommandStep.cpp
  src/runtime/RuntimeInteractionCommandFrameStep.cpp
  src/runtime/RuntimeInteractionCommandStep.cpp
  src/runtime/RuntimeInventoryState.cpp
  src/runtime/RuntimeInteractionState.cpp
  src/runtime/RuntimePolicyGameplayFrameStep.cpp
  src/runtime/RuntimePolicyGameplayFrameReporter.cpp
  src/runtime/RuntimePolicyGameplayFrameRunner.cpp
  src/runtime/RuntimePolicyPickupEffectFrameStep.cpp
  src/runtime/RuntimePolicyPickupEffectStep.cpp
  src/runtime/RuntimePolicyPickupStep.cpp
  src/runtime/RuntimePickupEffectFrameStep.cpp
  src/runtime/RuntimePickupEffectStep.cpp
  src/runtime/RuntimePickupStep.cpp
  src/runtime/RuntimeQueuedCommandRunner.cpp
  src/runtime/RuntimeQueuedMutationCommandRunner.cpp
  src/runtime/RuntimeSaveMetadata.cpp
  src/runtime/RuntimeSaveChunkArchive.cpp
  src/runtime/RuntimeSaveChunkArchiveCodec.cpp
  src/runtime/RuntimeSaveFormatVersionPolicy.cpp
  src/runtime/RuntimeSaveFileEnvelope.cpp
  src/runtime/RuntimeSaveFileIO.cpp
  src/runtime/RuntimeSaveSlotPathPolicy.cpp
  src/runtime/RuntimeSaveSlotDeletion.cpp
  src/runtime/RuntimeSaveSlotListing.cpp
  src/runtime/RuntimeSaveSlotRename.cpp
  src/runtime/RuntimeSaveSlotStore.cpp
  src/runtime/RuntimeLevelMutationStep.cpp
  src/runtime/RuntimeCollisionWorldProvider.cpp
  src/runtime/RuntimePlayerCommandExecutionStep.cpp
  src/runtime/RuntimePlayerCommandPlanningStep.cpp
  src/runtime/RuntimePlayerCommandStep.cpp
  src/runtime/RuntimePlayerInputFrameStep.cpp
  src/runtime/RuntimePlayerInputInteractionPolicyPickupFrameStep.cpp
  src/runtime/RuntimePlayerInputInteractionEffectApplyFrameStep.cpp
  src/runtime/RuntimePlayerInputInteractionEffectApplyFrameReporter.cpp
  src/runtime/RuntimePlayerInputInteractionEffectFrameStep.cpp
  src/runtime/RuntimePlayerInputInteractionEffectFrameReporter.cpp
  src/runtime/RuntimePlayerInputInteractionPickupFrameStep.cpp
  src/runtime/RuntimePlayerInputInteractionPickupFrameReporter.cpp
  src/runtime/RuntimePlayerInputInteractionFrameStep.cpp
  src/runtime/RuntimePlayerInputInteractionFrameReporter.cpp
  src/runtime/RuntimePlayerInputCommandRunner.cpp
  src/runtime/RuntimePlayerInputCommandReporter.cpp
  src/runtime/RuntimePlayerInputQueueStep.cpp
  src/runtime/RuntimeSessionCommandTick.cpp
  src/runtime/RuntimeSessionCommandTickRunner.cpp
  src/runtime/RuntimeSessionMutationCommandRunner.cpp
  src/runtime/RuntimeSessionMutationCommandStep.cpp
  src/runtime/RuntimeSessionSaveLoad.cpp
  src/runtime/RuntimeSessionSnapshot.cpp
  src/runtime/RuntimeSessionSnapshotChunkCodec.cpp
  src/runtime/RuntimeSessionSnapshotValidator.cpp
  src/runtime/RuntimeSessionState.cpp
  src/runtime/RuntimeSessionTick.cpp
  src/runtime/RuntimeSessionTickRunner.cpp
  src/runtime/RuntimeTick.cpp
  src/runtime/RuntimeTickRunner.cpp
)
